### PR TITLE
fix(hydration): ignore host scope token in `class` validation

### LINKED ISSUE #4853: Hydration mismatch when using dynamic `render()` and scoped styles
If you have a component with a dynamic `render()`, and if that `render()` function may return A) a template with scoped styles or B) a template without scoped styles, ~~and if A is not the default,~~ then you will see a hydration mismatch error:

```
Mismatch hydrating element <x-child>: attribute "class" has different values, 
expected "" but found "lwc-1o0kq40crvg-host"
```

The root cause seems to be that we validate the class attribute before we run the `render()` function. Before we run the `render()` function, we don't know what the stylesheet host token should be.

Interestingly, this does not occur for different HTML contents inside of the two different templates, because we run `render()` correctly _before_ we run `hydrateElement`/`hydrateStaticParts`/etc.

Repro: a9f9f560b

### PR DESCRIPTION
**Pull request by nolanlawson**
## Details

Fixes #4853

This is only a partial solution to the problem – I have a follow-up for further edge cases: https://github.com/salesforce/lwc/issues/4866

With this PR, when we render the host scope token (e.g. `class="lwc-abc123-host"`), we also encode it as a `data-lwc-host-scope-token` attribute. This tells hydration to ignore certain classes during `class` validation, which avoids timing issues when using scoped styles and `render()`.

To solve this, I'm also simplifying our class validation logic to only look at the differences between two `Set<string>`s. I just don't think it's worth it to care about classes in different orders, or duplicate classes – this doesn't affect CSS styling, and it makes the logic much simpler.

## Does this pull request introduce a breaking change?

-   😮‍💨 No, it does not introduce a breaking change.

## Does this pull request introduce an observable change?

-   🤞 No, it does not introduce an observable change.

### CODE REVIEW

File: packages/@lwc/engine-core/src/framework/hydration.ts [hunk 1]
```diff
@@ -627,92 +628,79 @@ function validateClassAttr(
...
+
+    // ---------- Step 1: get the classes from the element and the vnode
+
+    // Use a Set because we don't care to validate mismatches for 1) different ordering in SSR vs CSR, or 2)
+    // duplicated class names. These don't have an effect on rendered styles.
+    const elmClasses = new Set(ArrayFrom(elm.classList));
+    let vnodeClasses: Set<string>;
+
+    if (!isUndefined(className)) {
+        vnodeClasses = new Set(ArrayFilter.call(StringSplit.call(className, /\s+/), Boolean));
```
Comment (nolanlawson) [inline packages/@lwc/engine-core/src/framework/hydration.ts:642]:
```suggestion
        // ignore empty spaces entirely, filter them out using `filter(..., Boolean)`
        vnodeClasses = new Set(ArrayFilter.call(StringSplit.call(className, /\s+/), Boolean));
```

**Review by ekashida — APPROVED** [review]
