### PR TITLE
fix(rollup-plugin): allow any implicit HTML import from any kind of script file @W-15941938

### LINKED ISSUE #4233: Inherited template not found when using TypeScript and Babel
### Description
As TypeScript is not fully supported by LWC and the LWC rollup plugin we need to use Babel to remove the TypeScript annotation before the LWC rollup plugin can process it. This works fine when we have discrete components that implement both the javascript class and the html template.
The problem only occurs when we have one LWC component extending another LWC component and inheriting the html template from the parent component. Rollup throws an error that the template file cannot be found. It tries to find the html template for the child component instead of trying to load the template from the parent component.
This issue only happens when using TypeScript.

On the playground repro below you will see the error message `ENOENT: no such file or directory, open '/home/projects/salesforce-lwc-k2agyu/src/test/btnExtended/btnExtended.html'`.

I have created a workaround rollup plugin with the hardcoded path for the correct template as in the code snippet below.
If you uncomment those lines in the rollup config on the playground below the error goes away and the example works.

#### Steps to Reproduce

https://stackblitz.com/edit/salesforce-lwc-k2agyu?file=rollup.config.mjs

```js
    (() => ({
      name: "proxy-templates",
      resolveId: {
        order: "pre",
        handler(source) {
          if (source === "./btnExtended.html") {
            return path.resolve("src/test/button/button.html");
          }

          return null;
        }
      }
    }))()
```

#### Expected Results

No errors are thrown and the components work.

#### Actual Results

Rollup throws the error:
```bash
[!] Error: Could not load /home/projects/salesforce-lwc-k2agyu/src/test/btnExtended/btnExtended.html (imported by src/test/btnExtended/btnExtended.ts): ENOENT: no such file or directory, open '/home/projects/salesforce-lwc-k2agyu/src/test/btnExtended/btnExtended.html'
```

### Browsers Affected

N/A

### Version

- Node 18.20.3
- LWC: 6.6.3
- rollup: 3.28.0
- @rollup/plugin-babel: 6.0.4

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

### PR DESCRIPTION
**Pull request by wjhsf**
To detect whether a component is using an implicit HTML import, we check that it's a `.js` file. But that's not the only kind of script file that can be used! This PR adds support for all flavors of JS/TS/JSX that we might expect to encounter.

Fixes #4233.

## Does this pull request introduce a breaking change?

-   😮‍💨 No, it does not introduce a breaking change.

## Does this pull request introduce an observable change?

-   🔬 Yes, it does include an observable change.

## GUS work item

W-15941938

### CODE REVIEW

File: packages/@lwc/rollup-plugin/src/index.ts [hunk 1]
```diff
@@ -65,13 +65,15 @@ const IMPLICIT_DEFAULT_HTML_PATH = '@lwc/resources/empty_html.js';
 const EMPTY_IMPLICIT_HTML_CONTENT = 'export default void 0';
 const IMPLICIT_DEFAULT_CSS_PATH = '@lwc/resources/empty_css.css';
 const EMPTY_IMPLICIT_CSS_CONTENT = '';
+/** Matches all permutations of CJS/ESM, JS/TS, JS/JSX. */
+const SCRIPT_FILE_EXTENSION_REGEX = /^\.[cm]?[jt]sx?$/i;
```
Comment (ekashida) [inline packages/@lwc/rollup-plugin/src/index.ts:69]: Can we simplify this to something that uses an explicit list of extensions that doesn't require a comment?

Comment (nolanlawson) [reply packages/@lwc/rollup-plugin/src/index.ts:69]: Also, if we're going to support `.cjs`/ `.mjs` / etc., we should add it to this list as well:

https://github.com/salesforce/lwc/blob/c9aa701f3557cb7160a8ab86fc3772289821241a/packages/%40lwc/compiler/src/transformers/transformer.ts#L125-L128

Comment (nolanlawson) [reply packages/@lwc/rollup-plugin/src/index.ts:69]: Plus, I don't think we support `.cjs` anyway? The `@lwc/babel-plugin-component` will explode if it encounters CommonJS (e.g. `const { LightningElement } = require('lwc')`).

File: packages/@lwc/rollup-plugin/src/__tests__/resolver/resolver.spec.ts [hunk 2]
```diff
@@ -231,4 +231,32 @@ describe('resolver', () => {
...
+            input: path.resolve(__dirname, 'fixtures/inherited-templates/src/typescript.ts'),
+            plugins: [lwc()],
+        });
+
+        const result = await bundle.generate({
+            format: 'esm',
+        });
+        const { code } = result.output[0];
+
+        expect(code).toContain('all your base');
```
Comment (nolanlawson) [inline packages/@lwc/rollup-plugin/src/__tests__/resolver/resolver.spec.ts:260]: Are they belong to us?

**Review by nolanlawson — APPROVED** [review]

File: packages/@lwc/rollup-plugin/src/index.ts [hunk 3]
```diff
@@ -65,13 +65,14 @@ const IMPLICIT_DEFAULT_HTML_PATH = '@lwc/resources/empty_html.js';
 const EMPTY_IMPLICIT_HTML_CONTENT = 'export default void 0';
 const IMPLICIT_DEFAULT_CSS_PATH = '@lwc/resources/empty_css.css';
 const EMPTY_IMPLICIT_CSS_CONTENT = '';
+const SCRIPT_FILE_EXTENSIONS = ['.js', '.mjs', '.jsx', '.ts', '.mts', '.tsx'];
```
Comment (nolanlawson) [inline packages/@lwc/rollup-plugin/src/index.ts:68]: `Set` / `has` may be faster, but maybe not since this is a tiny list anyway.
