### PR TITLE
fix(ssr-compiler): conflicting type definitions for estree

### LINKED ISSUE #4773: Removal of "vitest/globals" results in conflicting type definition
### Description

As of #4740, the `PropertyDescriptor` type used during rollup bundling no longer has a `decorators` property.

Things that were noticed:

`@types/estree` defines a `PropertyDescriptor` without the `decorators` property

Screenshot 2024-11-01 at 18 11 14

`rollup` overrides `estree` with a `PropertyDescriptor` that does have the `decorators` property

Screenshot 2024-11-01 at 18 10 16

It's not clear why rollup is throwing the error when it's the one that has the desired type definition.

#### Steps to Reproduce

Add a reference to `path.node.decorators` somewhere in this [file](https://github.com/salesforce/lwc/blob/2f95ce2def446d3b46ca55682ab38fe430b4e773/packages/%40lwc/ssr-compiler/src/compile-js/index.ts#L53-L67).

```sh
$ yarn
...
$ rollup --config ../../../scripts/rollup/rollup.config.js

      /Users/ekashida/Repos/lwc/packages/@lwc/ssr-compiler/src/index.ts → dist/index.js, dist/index.cjs.js...
      [!] (plugin typescript) RollupError: [plugin typescript] src/compile-js/index.ts (78:59): @rollup/plugin-typescript TS2339: Property 'decorators' does not exist on type 'PropertyDefinition'.
      src/compile-js/index.ts (78:59)

      78         const decorators = (node as EsPropertyDefinition).decorators;
                                                                   ~~~~~~~~~~

          at getRollupError (/Users/ekashida/Repos/lwc/node_modules/rollup/dist/shared/parseAst.js:285:41)
          at Object.error (/Users/ekashida/Repos/lwc/node_modules/rollup/dist/shared/parseAst.js:281:42)
          at Object.error (/Users/ekashida/Repos/lwc/node_modules/rollup/dist/shared/rollup.js:902:32)
          at emitDiagnostic (/Users/ekashida/Repos/lwc/node_modules/@rollup/plugin-typescript/dist/cjs/index.js:571:17)
          at reportDiagnostics (/Users/ekashida/Repos/lwc/node_modules/@rollup/plugin-typescript/dist/cjs/index.js:579:9)
          at Array.forEach (<anonymous>)
          at emitFilesAndReportErrors (/Users/ekashida/Repos/lwc/node_modules/typescript/lib/typescript.js:127124:17)
          at Object.result.afterProgramCreate (/Users/ekashida/Repos/lwc/node_modules/typescript/lib/typescript.js:127283:7)
          at Object.afterProgramCreate (/Users/ekashida/Repos/lwc/node_modules/@rollup/plugin-typescript/dist/cjs/index.js:738:29)
          at synchronizeProgram (/Users/ekashida/Repos/lwc/node_modules/typescript/lib/typescript.js:127652:14)


error Command failed with exit code 1.
```

#### Expected Results

No errors thrown.

#### Actual Results

Error is thrown.

### Version

-   v8.6.0

### PR DESCRIPTION
**Pull request by cardoso**
## Details

Closes #4773

## Does this pull request introduce a breaking change?

-   😮‍💨 No, it does not introduce a breaking change.

## Does this pull request introduce an observable change?

-   🤞 No, it does not introduce an observable change.

### CODE REVIEW

File: packages/@lwc/ssr-compiler/src/compile-js/index.ts [hunk 1]
```diff
@@ -57,7 +57,7 @@ const visitors: Visitors = {
         }
 
         // TODO [#4773]: Why do we get conflicting PropertyDefinition types when removing "vitest/globals"?
```
Comment (wjhsf) [inline packages/@lwc/ssr-compiler/src/compile-js/index.ts:59]:
```suggestion
```
✅

**Review by nolanlawson — APPROVED** [review]
Nice find!
