### PR TITLE
fix: focus method invocation inside shadow should not skip shadow

### LINKED ISSUE #1370: [delegatesFocus] Account for programmatic focus
### Description

Our delegatesFocus polyfill currently only accounts for two cases: sequential focus navigation and focus placement via mouse clicks. Programmatically focusing on an element incorrectly executes the code path for sequential focus navigation when it should be treated more like a mouse click. The main difference between the two is that sequential focus navigation accounts for the previously focused element when determining what the next focusable element is. Clicks and programmatic focus simply move the focus to the specified target.

### PR DESCRIPTION
**Pull request by ekashida**
## Details

 Fixes #1370 

## Does this PR introduce breaking changes?

* ✅ `No, it does not introduce breaking changes.`

## The PR fulfills these requirements:
* Have tests for the proposed changes been added? ✅
* Have you followed [these instructions](../CONTRIBUTING.md#-commit-message-conventions) to clearly describe the issue being fixed or feature enhanced? ✅

### CODE REVIEW

File: packages/@lwc/synthetic-shadow/src/faux-shadow/focus.ts [hunk 1]
```diff
@@ -166,7 +169,20 @@ function focusOnNextOrBlur(
     }
 }
 
-function keyboardFocusHandler(event: FocusEvent) {
+let letBrowserHandleFocus: boolean = false;
+export function disableKeyboardFocusNavigationRoutines() {
```
Comment (ravijayaramappa) [inline packages/@lwc/synthetic-shadow/src/faux-shadow/focus.ts]:
```suggestion
export function disableKeyboardFocusNavigationRoutines(): void {
```

File: packages/@lwc/synthetic-shadow/src/faux-shadow/focus.ts [hunk 2]
```diff
@@ -166,7 +169,20 @@ function focusOnNextOrBlur(
...
+    letBrowserHandleFocus = true;
+}
+export function enableKeyboardFocusNavigationRoutines() {
```
Comment (ravijayaramappa) [inline packages/@lwc/synthetic-shadow/src/faux-shadow/focus.ts]:
```suggestion
export function enableKeyboardFocusNavigationRoutines(): void {
```
