### PR TITLE
fix(engine-dom): use native lifecycle callbacks

### LINKED ISSUE #3198: Use native `connectedCallback`/`disconnectedCallback` lifecycle hooks
We use non-standard mechanisms to trigger `connectedCallback`/`disconnectedCallback`. We should just use the native mechanism instead.

https://github.com/salesforce/lwc/blob/551f6349421f3cfaf4e8c4a8d3d393b7549bb0ab/packages/@lwc/engine-dom/src/apis/create-element.ts#L50-L72

This has implications for backwards compat, because the timing and other subtleties will be different.

Related: https://github.com/salesforce/lwc/issues/2609, https://github.com/salesforce/lwc/issues/1102, https://github.com/salesforce/lwc/pull/2709

Also related: #2986 which added a flag, without making the flag true by default.

### PR DESCRIPTION
**Pull request by nolanlawson**
## Details

BREAKING CHANGE: Use native custom element lifecycle for API version >=61.

Fixes #3198. New version of #3662. The umpteenth attempt to land this thing.

## Does this pull request introduce a breaking change?

* 🚨 Yes, it does introduce a breaking change.

All details are catalogued in #3662. The only difference this time is that this is for API version 61 rather than 60.

## Does this pull request introduce an observable change?

* ⚠️ Yes, it does include an observable change.

See above.

### CODE REVIEW

File: packages/@lwc/engine-core/src/framework/vm.ts [hunk 1]
```diff
@@ -280,7 +286,11 @@ function resetComponentStateWhenRemoved(vm: VM) {
 // old vnode.children is removed from the DOM.
 export function removeVM(vm: VM) {
     if (process.env.NODE_ENV !== 'production') {
-        if (!lwcRuntimeFlags.ENABLE_NATIVE_CUSTOM_ELEMENT_LIFECYCLE) {
+        if (
+            !shouldUseNativeCustomElementLifecycle(
```
Comment (jmsjtu) [inline packages/@lwc/engine-core/src/framework/vm.ts:290]: @nolanlawson do you think it would it be worth it to cache the value on VM?

File: packages/@lwc/engine-dom/src/custom-elements/create-custom-element.ts [hunk 2]
```diff
@@ -39,34 +39,34 @@ const createUpgradableConstructor = () => {
...
 
-        constructor(upgradeCallback: LifecycleCallback) {
+        constructor(upgradeCallback: LifecycleCallback, useNativeLifecycle: boolean) {
             super();
+
+            if (useNativeLifecycle) {
+                // When in native lifecycle mode, we need to keep track of instances that were created outside LWC
+                // (i.e. not created by `lwc.createElement()`). If the element uses synthetic lifecycle, then we don't
+                // need to track this.
+                nativeLifecycleElementsToUpgradedByLWC.set(this, elementBeingUpgradedByLWC);
```
Comment (jmsjtu) [inline packages/@lwc/engine-dom/src/custom-elements/create-custom-element.ts:49]: Nice!

File: packages/@lwc/engine-core/src/framework/vm.ts (hunk 1 above)
Comment (nolanlawson) [reply packages/@lwc/engine-core/src/framework/vm.ts:290]: I don't think so, so. I don't think computing this should be very expensive – it's just about comparing integer values mostly.

File: packages/@lwc/engine-dom/src/custom-elements/create-custom-element.ts (hunk 2 above)
Comment (nolanlawson) [reply packages/@lwc/engine-dom/src/custom-elements/create-custom-element.ts:49]: Yeah I was pleased that I was able to do this with just one `Map`!

**Review by jmsjtu — APPROVED** [review]
