### PR TITLE
fix(signals): avoid throwing when `in` check throws

### LINKED ISSUE #5104: Experimental signals error: "Blocked a frame with origin "..." from accessing a cross-origin frame"
### Description

If the `lwcRuntimeFlags.ENABLE_EXPERIMENTAL_SIGNALS` flag is enabled, and if a property is set on a component which corresponds to the `contentWindow` of a cross-origin iframe where cross-origin access is blocked (e.g. via `sandbox=''`), then LWC throws an error during rendering:

```
Uncaught SecurityError: Blocked a frame with origin "..." from accessing a cross-origin frame.
```

#### Steps to Reproduce

Minimal repro:

```js
export default class App extends LightningElement {

  foo

  constructor() {
    super()

    const iframe = document.createElement('iframe')
    iframe.sandbox = ''
    iframe.src = 'https://example.com'
    document.body.appendChild(iframe)
    this.foo = iframe.contentWindow
  }

  renderedCallback() {
    console.log(this.foo)
  }
}
```

[Live repro](https://stackblitz.com/edit/salesforce-lwc-bmphyxgh?file=src%2Fmodules%2Fx%2Fapp%2Fapp.js,src%2Fmain.js&title=LWC%20playground)

https://playground.lwc.dev

```js
const your => (code) => here;
```

#### Expected Results

No error

#### Actual Results

Error thrown

#### Possible Solution

To work around this, you can set a different object than the `contentWindow` to be the property on a component. For example:

```diff
- this.foo = iframe.contentWindow
+ this.foo = { window: iframe.contentWindow }
```

### PR DESCRIPTION
**Pull request by nolanlawson**
## Details

Fixes #5104

Avoids throwing an error when the `in` operator throws an error on an arbitrary object.

This should not cause any breaking changes, because we are trying to detect if an object "looks" like a signal, and if checking `'value' in object` throws, then we can conclusively say it's not a signal.

## Does this pull request introduce a breaking change?

- 😮‍💨 No, it does not introduce a breaking change.

## Does this pull request introduce an observable change?

- 🤞 No, it does not introduce an observable change.

### CODE REVIEW

File: packages/@lwc/engine-core/src/framework/utils.ts [hunk 1]
```diff
@@ -104,3 +104,13 @@ export function shouldBeFormAssociated(Ctor: LightningElementConstructor) {
 
     return ctorFormAssociated && apiFeatureEnabled;
 }
+
+// check if a property is in an object, and if the object throws an error merely because we are
+// checking if the property exists, return false
+export function safeHasProp(obj: any, prop: string) {
```
Comment (wjhsf) [inline packages/@lwc/engine-core/src/framework/utils.ts:110]:
```suggestion
export function safeHasProp<T extends object, K extends PropertyKey>(obj: T, prop: K): obj is Record<K, unknown> {
```

File: packages/@lwc/engine-core/src/framework/mutation-tracker.ts [hunk 2]
```diff
@@ -34,16 +35,16 @@ export function componentValueObserved(vm: VM, key: PropertyKey, target: any = {
...
     if (
         lwcRuntimeFlags.ENABLE_EXPERIMENTAL_SIGNALS &&
         isObject(target) &&
         !isNull(target) &&
-        'value' in target &&
-        'subscribe' in target &&
-        isFunction(target.subscribe) &&
+        safeHasProp(target, 'value') &&
+        safeHasProp(target, 'subscribe') &&
+        isFunction((target as any).subscribe) &&
```
Comment (wjhsf) [inline packages/@lwc/engine-core/src/framework/mutation-tracker.ts:47]:
```suggestion
        isFunction(target.subscribe) &&
```
Not necessary with better types for `safeHasProp`

**Review by wjhsf — APPROVED** [review]

File: packages/@lwc/engine-core/src/framework/utils.ts (hunk 1 above)
Comment (nolanlawson) [reply packages/@lwc/engine-core/src/framework/utils.ts]: I tried to do this but failed. `Record` was the thing I was missing!

Comment (nolanlawson) [reply packages/@lwc/engine-core/src/framework/utils.ts]: TypeScript is still angry

Screenshot 2025-01-08 at 9 54 34 AM

Comment (nolanlawson) [reply packages/@lwc/engine-core/src/framework/utils.ts]: 5edfa007f
