### PR TITLE
fix(template-compiler): handle comments in lwc:dom

### LINKED ISSUE #2415: `lwc:dom="manual"` with a comment as children throws "Element must be empty"
#### Steps to Reproduce
1. Create an LWC component with `lwc:dom="manual"` and nest a comment in it.

```html
<template>
  <div lwc:dom="manual"> <!-- comment here --></div>
</template>
```

#### Expected Results
No error is thrown

#### Actual Results
"LWC1086: Invalid contents for element with "lwc:dom". Element must be empty" is thrown.

### Version

- LWC: x.x.x

**Possible Solution**

**Additional context/Screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.

### PR DESCRIPTION
**Pull request by abdulsattar**
## Details
Fixes #2415 

## Does this PR introduce breaking changes?

* ✅ `No, it does not introduce breaking changes.`

If yes, please describe the impact and migration path for existing applications.

## The PR fulfills these requirements:
* Have tests for the proposed changes been added? ✅
* Have you followed [these instructions](../CONTRIBUTING.md#-commit-message-conventions) to clearly describe the issue being fixed or feature enhanced? ✅

### CODE REVIEW

File: packages/@lwc/template-compiler/src/parser/index.ts [hunk 1]
```diff
@@ -882,7 +882,11 @@ export default function parse(source: string, state: State): TemplateParseResult
     }
 
     function validateChildren(element: IRElement) {
-        if (element.lwc?.dom && element.children.length > 0) {
+        if (!element.lwc?.dom) return;
+        const children = getPreserveComments(element)
+            ? element.children
+            : element.children.filter((child) => child.type !== 'comment');
+        if (children.length > 0) {
```
Comment (pmdartus) [inline packages/@lwc/template-compiler/src/parser/index.ts:889]: As this method is only about the `lwc:dom` directive and since we might add more validation steps later and I would recommend removing the early exit.

```suggestion
        const effectiveChildren = getPreserveComments(element)
            ? element.children
            : element.children.filter((child) => child.type !== 'comment');
        if (element.lwc?.dom && effectiveChildren.length > 0) {
```

**Review by pmdartus — APPROVED** [review]
Small nitpick otherwise LGTM.
