### PR TITLE
fix: throw error if Rollup version is too old

### LINKED ISSUE #2505: @lwc/rollup-plugin fails to build on Rollup <v2.29.0
### Description

In versions of Rollup prior to v2.29.0, `@lwc/rollup-plugin` will throw an error as of LWC v2.5.0:

    TypeError: Cannot read property 'lwcScopedStyles' of undefined

At this line:

https://github.com/salesforce/lwc/blob/66a26f6a8863905d60630bf604cc4761ac345c60/packages/%40lwc/rollup-plugin/src/index.js#L120

#### Steps to Reproduce

Change the Rollup version in this project's `package.json` to 2.28.2 or less, then run:

    yarn && npx jest --config ./scripts/jest/root.config.js ./packages/@lwc/rollup-plugin/

**Possible Solution**

Update Rollup to v2.29.0 or above.

### PR DESCRIPTION
**Pull request by nolanlawson**
## Details

Fixes #2505

This PR updates the min semver in the `peerDependencies` Rollup version for `@lwc/rollup-plugin`, and improves the error message if the Rollup version is too old.

## Does this PR introduce breaking changes?

* ✅ `No, it does not introduce breaking changes.`

### CODE REVIEW

**Comment by nolanlawson** [comment]
I tested this manually by downgrading Rollup, and it throws an error like:

    @lwc/rollup-plugin requires Rollup version ^2.29.0 (found: 2.28.0). Please update Rollup.

**Review by jye-sf — APPROVED** [review]

File: packages/@lwc/rollup-plugin/src/index.js [hunk 1]
```diff
@@ -56,6 +58,11 @@ module.exports = function rollupLwcCompiler(pluginOptions = {}) {
         },
 
         resolveId(importee, importer) {
+            if (!semver.satisfies(this.meta.rollupVersion, pkg.peerDependencies.rollup)) {
```
Comment (pmdartus) [inline packages/@lwc/rollup-plugin/src/index.js:61]: This check will run every time rollup resolves a file which is not ideal. I can either be moved to the `buildStart` or the `options` rollup hook to only run once per build.

**Review by pmdartus — CHANGES_REQUESTED** [review]

File: packages/@lwc/rollup-plugin/src/index.js (hunk 1 above)
Comment (nolanlawson) [reply packages/@lwc/rollup-plugin/src/index.js:61]: Thanks, moved it to `buildStart` as that seems like the most logical place to put it.

File: packages/@lwc/rollup-plugin/package.json [hunk 2]
```diff
@@ -22,10 +22,11 @@
     },
     "dependencies": {
         "@lwc/module-resolver": "2.5.1",
-        "@rollup/pluginutils": "~4.1.1"
+        "@rollup/pluginutils": "~4.1.1",
+        "semver": "^7.3.5"
     },
     "peerDependencies": {
-        "rollup": "^1.2.0||^2.0.0"
+        "rollup": "^2.29.0"
```
[the remark this answers is not in the document]
Comment (pmdartus) [reply packages/@lwc/rollup-plugin/package.json:29]: Yes, I think so. The `meta` context was added with this [PR](https://github.com/rollup/rollup/pull/3807) which landed in the `2.29.0` release.

**Review by pmdartus — APPROVED** [review]

**Review by ekashida — APPROVED** [review]
