### PR TITLE
fix(engine-core): fix timing of ref resets

### LINKED ISSUE #3796: [3.7.0 regression] Re-rendering causes `this.refs.foo` to become `undefined`
### Description

When reactivity causes the component to re-render, `this.refs.foo` can become undefined.

#### Steps to Reproduce

```html
<template>
  <div lwc:ref="foo"></div>
  <div>{bar}</div>
</template>
```

```js
export default class extends LightningElement {
  bar = 0
  connectedCallback() {
    setInterval(() => {
      this.bar = this.bar + 1
      console.log('this.refs.foo', this.refs.foo) // becomes undefined
    }, 1000)
  }
}
```

- [Repro in 3.7.1](https://stackblitz.com/edit/salesforce-lwc-2futzm?file=src%2Fmodules%2Fx%2Fapp%2Fapp.html,src%2Fmodules%2Fx%2Fapp%2Fapp.js,package.json&title=LWC%20playground) (fails)
- [Repro in 3.6.0](https://stackblitz.com/edit/salesforce-lwc-ljwqvr?file=src%2Fmodules%2Fx%2Fapp%2Fapp.html,src%2Fmodules%2Fx%2Fapp%2Fapp.js,package.json&title=LWC%20playground) (succeeds)

This was probably caused by #3694.

### PR DESCRIPTION
**Pull request by nolanlawson**
## Details

Fixes #3796

This is an alternative to #3797 – it's a fix-forward rather than a revert.

I also added in the same tests.

I guess I'm waiting to see if both PRs pass CI, and then we can decide if we want to fix-forward or revert.

## Does this pull request introduce a breaking change?

* ✅ No, it does not introduce a breaking change.

## Does this pull request introduce an observable change?

* ✅ No, it does not introduce an observable change.

## GUS work item
[W-14294276](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001cOeCwYAK/view)

### CODE REVIEW

File: packages/@lwc/engine-core/src/framework/modules/static-parts.ts [hunk 1]
```diff
@@ -84,12 +90,17 @@ export function applyStaticParts(root: Element, vnode: VStatic, renderer: Render
         return;
     }
 
-    traverseAndSetElements(root, parts, renderer); // this adds `part.elm` to each `part`
+    // This adds `part.elm` to each `part`. We have to do this on every mount/patch because the `parts`
+    // array is recreated from scratch every time, so each `part.elm` is now undefined.
+    traverseAndSetElements(root, parts, renderer);
```
Comment (nolanlawson) [inline packages/@lwc/engine-core/src/framework/modules/static-parts.ts:95]: I'm not super happy with this, since it means we are traversing every time we patch the static content (which kind of defeats the purpose of the static content). But I don't have any good ideas for optimizing this right now.

Comment (nolanlawson) [reply packages/@lwc/engine-core/src/framework/modules/static-parts.ts:95]: We could keep a cache of the static refs or something, but I don't know how much time this will save in practice. `traverseAndSetElements` is already pretty fast (0.3ms total for our entire Karma test suite).

Comment (nolanlawson) [reply packages/@lwc/engine-core/src/framework/modules/static-parts.ts:95]: Maybe we could just build a `Map<number,Element>` once. This would be a significant refactor though – probably better for another PR.

File: packages/@lwc/integration-karma/test/component/refs/index.spec.js [hunk 2]
```diff
@@ -333,10 +335,32 @@ describe('refs', () => {
...
+                is: RerenderElementStaticRef,
+            });
+            document.body.appendChild(elm);
+
+            await Promise.resolve();
+
+            const fooDiv = elm.getRef('foo');
+            expect(fooDiv).not.toBeUndefined();
+
+            expect(elm.getRef('foo')).toBe(fooDiv);
```
Comment (divmain) [inline packages/@lwc/integration-karma/test/component/refs/index.spec.js:355]: I'm not sure I understand the reason behind this assertion. Was `elm.getRef('foo')` returning `undefined` on a second non-async call to `getRef`? It doesn't hurt anything, I just want to understand. It reads like `expect(thing).toBe(thing)`.

**Review by divmain — APPROVED** [review]
LGTM. Only ask would be to capture the ways in which this change detracts from any perf wins, and stick that in an issue or WI.

File: packages/@lwc/integration-karma/test/component/refs/index.spec.js (hunk 2 above)
Comment (nolanlawson) [reply packages/@lwc/integration-karma/test/component/refs/index.spec.js:355]: yeah this was a mistake on my part

File: packages/@lwc/engine-core/src/framework/modules/static-parts.ts (hunk 1 above)
Comment (nolanlawson) [reply packages/@lwc/engine-core/src/framework/modules/static-parts.ts:95]: https://github.com/salesforce/lwc/issues/3800
