### PR TITLE
refactor: fix light dom slots for fragments

### LINKED ISSUE #3823: Light Dom slots don't trigger `disconnectedCallback` in synthetic lifecycle
### Description

Now that light DOM slots use fragments (#3649), they don't trigger `disconnectedCallback` when `ENABLE_NATIVE_CUSTOM_ELEMENT_LIFECYCLE` is not set.

#### Steps to Reproduce

Repro:

https://stackblitz.com/edit/salesforce-lwc-fcxo47?file=src%2Fmain.js

In the above example, the `disconnectedCallback` should be invoked when swapping between the if conditions.

### PR DESCRIPTION
**Pull request by jmsjtu**
## Details
Partially fixes #3823, the synthetic lifecycle will not call `disconnectedCallback` but does bring it back to parity with the behavior from LWC 3.x.x.

A followup PR will fully resolve #3823.

## Does this pull request introduce a breaking change?

* ✅ No, it does not introduce a breaking change.

## Does this pull request introduce an observable change?

* ⚠️ Yes, it does include an observable change.

This will allow `disconnectedCallback` to be invoked for light DOM slots, which was merged today so it shouldn't have a large impact.

### CODE REVIEW

File: packages/@lwc/engine-core/src/framework/rendering.ts [hunk 1]
```diff
@@ -518,6 +518,11 @@ function unmount(
             break;
         }
 
+        case VNodeType.Fragment: {
+            unmountVNodes(vnode.children, elm as ParentNode, renderer, false);
+            break;
+        }
```
Comment (jmsjtu) [inline packages/@lwc/engine-core/src/framework/rendering.ts:524]: In the `unmount` invocations, after the `doRemove` iteration, the vnodes are manually removed. 

Since there isn't a case for `VNodeType.Fragment`, it does not disconnect them.

This isn't an issue when `ENABLE_NATIVE_CUSTOM_ELEMENT_LIFECYCLE` is true because they will be invoked on `renderer.remove`.

File: packages/@lwc/engine-core/src/framework/rendering.ts [hunk 2]
```diff
@@ -518,6 +518,13 @@ function unmount(
             break;
         }
 
+        case VNodeType.Fragment: {
+            if (!lwcRuntimeFlags.ENABLE_NATIVE_CUSTOM_ELEMENT_LIFECYCLE) {
+                unmountVNodes(vnode.children, elm as ParentNode, renderer, false);
+            }
+            break;
+        }
```
Comment (jmsjtu) [inline packages/@lwc/engine-core/src/framework/rendering.ts:526]: In the unmount invocations, after the doRemove iteration, the vnodes are manually removed.

Since there isn't a case for VNodeType.Fragment, it does not disconnect them.

This isn't an issue when ENABLE_NATIVE_CUSTOM_ELEMENT_LIFECYCLE is true because they will be invoked on renderer.remove.

Comment (jmsjtu) [reply packages/@lwc/engine-core/src/framework/rendering.ts:526]: On second though we might want to wrap the `VNodeType.CustomElement` around the `ENABLE_NATIVE_CUSTOM_ELEMENT_LIFECYCLE` check too so it doesn't call `disconnectedCallback` twice.

File: packages/@lwc/integration-karma/test/rendering/callback-invocation-order/index.spec.js [hunk 3]
```diff
@@ -297,3 +299,90 @@ it('should invoke callbacks on the right order when multiple templates are used
...
+        is: LightContainerMultipleConditionals,
+    });
+    document.body.appendChild(container);
+
+    let currentLeafName = container.getLeaf().name;
+    expect(window.timingBuffer).toEqual([
+        'lightContainer:connectedCallback',
+        'lightSlot:connectedCallback',
+        `leaf:${currentLeafName}:connectedCallback`,
+    ]);
```
Comment (jmsjtu) [inline packages/@lwc/integration-karma/test/rendering/callback-invocation-order/index.spec.js:349]: These tests are a little strange, but I created them to capture the current behavior and ensure they match what happens in 3.x.x.

File: packages/@lwc/engine-core/src/framework/rendering.ts (hunk 2 above)
Comment (jmsjtu) [reply packages/@lwc/engine-core/src/framework/rendering.ts]: @nolanlawson I did some more testing and I added tests to ensure the behavior is the same between LWC 4.x.x and 3.x.x.

File: packages/@lwc/integration-karma/test/rendering/callback-invocation-order/index.spec.js (hunk 3 above)
Comment (jmsjtu) [reply packages/@lwc/integration-karma/test/rendering/callback-invocation-order/index.spec.js:349]: Note that this bug only occurs if the conditional rendering occurs on the same component as the `<slot>` element.

The bug also only occurs when the condition is only triggered through the component containing the `<slot>`.

If the condition depends on a value being passed from a parent component, the slots will render correctly.

File: packages/@lwc/integration-karma/test/rendering/callback-invocation-order/index.spec.js [hunk 4]
```diff
@@ -297,3 +299,90 @@ it('should invoke callbacks on the right order when multiple templates are used
             ]);
         });
 });
+
+if (process.env.NATIVE_SHADOW) {
```
Comment (nolanlawson) [inline packages/@lwc/integration-karma/test/rendering/callback-invocation-order/index.spec.js:303]: Rather than run this test only in native shadow, I would prefer we run it in both and validate the behavior difference between the two. We can still reference the bug in a comment.

File: packages/@lwc/integration-karma/test/rendering/callback-invocation-order/index.spec.js [hunk 5]
```diff
@@ -297,3 +299,90 @@ it('should invoke callbacks on the right order when multiple templates are used
...
+        'lightSlot:connectedCallback',
+        `leaf:${currentLeafName}:connectedCallback`,
+    ]);
+
+    resetTimingBuffer();
+
+    const slotCmp = container.getSlotCmp();
+    slotCmp.showIf = true;
+
+    return Promise.resolve()
```
Comment (nolanlawson) [inline packages/@lwc/integration-karma/test/rendering/callback-invocation-order/index.spec.js:356]: You can use async/await in these tests (i.e. `await Promise.resolve()`). It makes things way cleaner IMO.

File: packages/@lwc/integration-karma/test/rendering/callback-invocation-order/index.spec.js [hunk 6]
```diff
@@ -297,3 +299,90 @@ it('should invoke callbacks on the right order when multiple templates are used
...
+            slotCmp.showIf = false;
+        })
+        .then(() => {
+            currentLeafName = container.getLeaf().name;
+            expect(window.timingBuffer).toEqual([
+                `leaf:${currentLeafName}:connectedCallback`,
+                `leaf:${currentLeafName}:disconnectedCallback`,
+            ]);
+
+            document.body.removeChild(container);
```
Comment (nolanlawson) [inline packages/@lwc/integration-karma/test/rendering/callback-invocation-order/index.spec.js:386]: This is not strictly necessary – the test setup code will remove the container automatically in an `afterEach`.

File: packages/@lwc/integration-karma/test/rendering/callback-invocation-order/index.spec.js [hunk 7]
```diff
@@ -297,3 +299,90 @@ it('should invoke callbacks on the right order when multiple templates are used
...
+                window.lwcRuntimeFlags.ENABLE_NATIVE_CUSTOM_ELEMENT_LIFECYCLE
+                    ? [
+                          `leaf:${currentLeafName}:connectedCallback`,
+                          `leaf:${previousLeafName}:disconnectedCallback`,
+                          `leaf:${currentLeafName}:disconnectedCallback`,
+                      ]
+                    : [
+                          `leaf:${currentLeafName}:connectedCallback`,
+                          `leaf:${currentLeafName}:disconnectedCallback`,
+                      ]
```
Comment (nolanlawson) [inline packages/@lwc/integration-karma/test/rendering/callback-invocation-order/index.spec.js:371]: So the previous leaf never fires a disconnectedCallback? I thought this was the entire bug?

**Review by nolanlawson — APPROVED** [review]
This LGTM, since the behavior is the same as v3.x.

Since we have API versioning tests, and since the tests pass the same in both versions, we know this must be true! 😄

File: packages/@lwc/integration-karma/test/rendering/callback-invocation-order/index.spec.js (hunk 7 above)
Comment (jmsjtu) [reply packages/@lwc/integration-karma/test/rendering/callback-invocation-order/index.spec.js:371]: @nolanlawson yup, the previous leaf won't fire `disconnectedCallback` in synthetic lifecycle.

This is how it behaves in 3.x.x, this PR just brings the behavior back to what it was in 3.x.x.

I plan to raise another PR to fix the `disconnectedCallback` behavior entirely as part of #3832

Comment (nolanlawson) [reply packages/@lwc/integration-karma/test/rendering/callback-invocation-order/index.spec.js:371]: > I plan to raise another PR to fix the `disconnectedCallback` behavior entirely

Is this worth doing if we are going to do native lifecycle in 5.0?

Comment (jmsjtu) [reply packages/@lwc/integration-karma/test/rendering/callback-invocation-order/index.spec.js:371]: Yeah I think either way this will need to be fixed because if you look at the native lifecycle (one above this one) the new component is connected and immediately disconnected.

Which means all the components are disconnected after `unmount` runs.

Comment (jmsjtu) [reply packages/@lwc/integration-karma/test/rendering/callback-invocation-order/index.spec.js:371]: Also, this is a very specific bug, the rerender has to be isolated to just the component containing the `<slot>` element.

For example:

```html

<template>
    <template lwc:if={showMe}>
        <slot></slot>
    <template lwc:else>
        <slot></slot>
</template>
```
If the value of `showMe` is passed down from a parent component then this bug does not appear, but if the value of `showMe` is isolated to just the component, it does.

Comment (nolanlawson) [reply packages/@lwc/integration-karma/test/rendering/callback-invocation-order/index.spec.js:371]: > Yeah I think either way this will need to be fixed because if you look at the native lifecycle (one above this one) the new component is connected and immediately disconnected.

So is the issue that the diffing algo is doing extra unnecessary work?

File: packages/@lwc/integration-karma/test/rendering/callback-invocation-order/index.spec.js (hunk 6 above)
Comment (jmsjtu) [reply packages/@lwc/integration-karma/test/rendering/callback-invocation-order/index.spec.js]: Removed!

File: packages/@lwc/integration-karma/test/rendering/callback-invocation-order/index.spec.js (hunk 5 above)
Comment (jmsjtu) [reply packages/@lwc/integration-karma/test/rendering/callback-invocation-order/index.spec.js]: Updated in latest commit!

File: packages/@lwc/integration-karma/test/rendering/callback-invocation-order/index.spec.js (hunk 4 above)
Comment (jmsjtu) [reply packages/@lwc/integration-karma/test/rendering/callback-invocation-order/index.spec.js]: I updated in the latest commit to run both native and synthetic shadow.

File: packages/@lwc/integration-karma/test/rendering/callback-invocation-order/index.spec.js (hunk 7 above)
Comment (jmsjtu) [reply packages/@lwc/integration-karma/test/rendering/callback-invocation-order/index.spec.js]: Sort of, in this specific bug, the references to what's being slotted is getting mixed up, so when the element is removed from the DOM both native and synthetic lifecycles are called.
