### PR TITLE
fix(perf): avoid creating unnecessary sets @W-17361878

### LINKED ISSUE #4994: Improve perf of `class`-diffing during hydration
https://github.com/salesforce/lwc/pull/4865 introduced a regression in the `hydrate` benchmarks of [around 5-7%](https://docs.google.com/spreadsheets/d/1ftcekfI0DxE-Iu-0_NOoNr5fm1UoDjBDIVRpCxuWYsY/edit?gid=0#gid=0). This seems to be because we are creating empty `Set`s representing unique classes and then comparing them.

We should be able to optimize this by e.g. re-using a single constant empty `Set` rather than creating multiple.

Screenshot 2024-12-03 at 11 06 40 AM

### PR DESCRIPTION
**Pull request by wjhsf**
## Details

Fixes #4994.

## Does this pull request introduce a breaking change?

- 😮‍💨 No, it does not introduce a breaking change.

## Does this pull request introduce an observable change?

- 🤞 No, it does not introduce an observable change.

## GUS work item

W-17361878

### CODE REVIEW

File: packages/@lwc/engine-core/src/framework/hydration.ts [hunk 1]
```diff
@@ -63,6 +63,10 @@ import type {
 import type { VM } from './vm';
 import type { RendererAPI } from './renderer';
 
+type Classes = Omit<Set<string>, 'add'>;
+
+const EMPTY_SET: Classes = new Set<string>();
```
Comment (wjhsf) [inline packages/@lwc/engine-core/src/framework/hydration.ts:68]: We don't want to accidentally do `EMPTY_SET.add(something)`, so this is just a type hack to warn ourselves.

File: packages/@lwc/engine-core/src/framework/hydration.ts [hunk 2]
```diff
@@ -658,7 +682,11 @@ function validateClassAttr(
     // Consequently, hydration mismatches will occur if scoped CSS token classnames
     // are rendered during SSR. This needs to be accounted for when validating.
     if (!isNull(scopeToken)) {
-        vnodeClasses.add(scopeToken);
+        if (vnodeClasses === EMPTY_SET) {
+            vnodeClasses = new Set([scopeToken]);
+        } else {
+            (vnodeClasses as Set<string>).add(scopeToken);
+        }
```
Comment (wjhsf) [inline packages/@lwc/engine-core/src/framework/hydration.ts:689]: Not quite sure the best optimization for empty except the scoped token, so I just went with this.

File: packages/@lwc/engine-core/src/framework/hydration.ts [hunk 3]
```diff
@@ -618,6 +622,24 @@ function validateAttrs(
     return nodesAreCompatible;
 }
 
+function checkNodeCompatibility(first: Classes, second: Classes): boolean {
```
Comment (wjhsf) [inline packages/@lwc/engine-core/src/framework/hydration.ts:625]: Bonus optimization unrelated to the empty set, the previous implementation would check all items, even though we can short circuit after the first incompatibility found.

File: packages/@lwc/engine-core/src/framework/hydration.ts [hunk 4]
```diff
@@ -618,6 +622,24 @@ function validateAttrs(
...
+            if (!second.has(f)) {
+                return false;
+            }
+        }
+        for (const s of second) {
+            if (!first.has(s)) {
+                return false;
+            }
+        }
+    }
```
Comment (wjhsf) [inline packages/@lwc/engine-core/src/framework/hydration.ts:639]:
```suggestion
    for (const f of first) {
        if (!second.has(f)) {
            return false;
        }
    }
    for (const s of second) {
        if (!first.has(s)) {
            return false;
        }
    }
```

**Comment by wjhsf** [comment]
```rust
┌─────────────┬─────────────────┐
│     Browser │ chrome-headless │
│             │ 131.0.0.0       │
├─────────────┼─────────────────┤
│ Sample size │ 100             │
└─────────────┴─────────────────┘

┌───────────────────────────────────────────┬─────────────┬────────────┬───────────────────┬──────────────────────────────────────────────┬──────────────────────────────────────────────┐
│ Benchmark                                 │ Version     │ Bytes      │          Avg time │ vs hydration-tablecmp-hydrate-1k-this-change │ vs hydration-tablecmp-hydrate-1k-tip-of-tree │
│                                           │             │            │                   │                                              │                                  tip-of-tree │
├───────────────────────────────────────────┼─────────────┼────────────┼───────────────────┼──────────────────────────────────────────────┼──────────────────────────────────────────────┤
│ hydration-tablecmp-hydrate-1k-this-change │ <none>      │ 698.25 KiB │ 52.98ms - 53.84ms │                                              │                                       faster │
│                                           │             │            │                   │                                     -        │                                      3% - 5% │
│                                           │             │            │                   │                                              │                              1.69ms - 2.94ms │
├───────────────────────────────────────────┼─────────────┼────────────┼───────────────────┼──────────────────────────────────────────────┼──────────────────────────────────────────────┤
│ hydration-tablecmp-hydrate-1k-tip-of-tree │ tip-of-tree │ 698.00 KiB │ 55.27ms - 56.18ms │                                       slower │                                              │
│                                           │             │            │                   │                                      3% - 6% │                                     -        │
│                                           │             │            │                   │                              1.69ms - 2.94ms │                                              │
└───────────────────────────────────────────┴─────────────┴────────────┴───────────────────┴──────────────────────────────────────────────┴──────────────────────────────────────────────┘
```

File: packages/@lwc/engine-core/src/framework/hydration.ts (hunk 1 above)
Comment (nolanlawson) [reply packages/@lwc/engine-core/src/framework/hydration.ts:68]: Let's add a short comment explaining this optimization.

Comment (wjhsf) [inline packages/@lwc/engine-core/src/framework/hydration.ts:68]:
```suggestion
// Used as a perf optimization to avoid creating and discarding sets unnecessarily.
const EMPTY_SET: Classes = new Set<string>();
```

**Review by nolanlawson — APPROVED** [review]
