### PR TITLE
fix(style-compiler): upgrade postcss and cssnano

### LINKED ISSUE #1331: NPM Package Vulnerabilities Reported
#### Steps to Reproduce

```
npx lwc-create-app my-app
npm audit
```

#### Expected Results

No reported vulnerabilities.

#### Actual Results

```
                                                                                
                       === npm audit security report ===                        
                                                                                
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Denial of Service                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ js-yaml                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=3.13.0                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ lwc-services                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ lwc-services > @lwc/compiler > @lwc/style-compiler > cssnano │
│               │ > postcss-svgo > svgo > js-yaml                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/788                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Code Injection                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ js-yaml                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=3.13.1                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ lwc-services                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ lwc-services > @lwc/compiler > @lwc/style-compiler > cssnano │
│               │ > postcss-svgo > svgo > js-yaml                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/813                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 2 vulnerabilities (1 moderate, 1 high) in 889133 scanned packages
  2 vulnerabilities require manual review. See the full report for details.
```

### Browsers Affected

N/A

**Possible Solution**

Manually upgrade reported libraries; validate there are no negative impacts.

### PR DESCRIPTION
**Pull request by pmdartus**
## Details

This PR upgrades postcss and cssnano to the latest available version on NPM. 
Fixes #1331.

## Does this PR introduce breaking changes?

* ✅ `No, it does not introduce breaking changes.`

If yes, please describe the impact and migration path for existing applications.

## The PR fulfills these requirements:
* Have tests for the proposed changes been added? ✅
* Have you followed [these instructions](../CONTRIBUTING.md#-commit-message-conventions) to clearly describe the issue being fixed or feature enhanced? ✅

### CODE REVIEW

File: packages/@lwc/compiler/src/__tests__/fixtures/expected-minify-no-comments.js [hunk 1]
```diff
@@ -1 +1 @@
-define("x/comments",["lwc"],function(e){var t=[function(e,t,s){return(s?":host{color:blue}":e+"{color:blue}")+"x-comments"+t+"{color:green}"}];function s(e,t,s,n){const{d:o,h:r}=e;return[r("h1",{key:0},[o(t.myname)])]}var n=e.registerTemplate(s);s.stylesheets=[],t&&s.stylesheets.push.apply(s.stylesheets,t),s.stylesheetTokens={hostAttribute:"x-comments_comments-host",shadowAttribute:"x-comments_comments"};class o extends e.LightningElement{constructor(...e){super(...e),this.myname="default value"}}return e.registerDecorators(o,{track:{myname:1}}),e.registerComponent(o,{tmpl:n})});
```
Comment (caridy) [inline packages/@lwc/compiler/src/__tests__/fixtures/expected-minify-no-comments.js]: any reason for this test to be removed?

Comment (caridy) [reply packages/@lwc/compiler/src/__tests__/fixtures/expected-minify-no-comments.js]: I suspect it is a behavior change that might not be observable to the end-user since it is about comments.

Comment (pmdartus) [reply packages/@lwc/compiler/src/__tests__/fixtures/expected-minify-no-comments.js]: If you look into the diff, it's a line replacement, not a removal. The arguments identifier have been swapped out.

File: packages/@lwc/style-compiler/src/postcss-minify-plugins.ts [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+
+/**
+ * cssnano decided to make its APIs asynchronous with v4. Because the LWC compiler transform API is
+ * synchronous we can't use cssnano directly. For now we use the css-nano-preset-default and filter
+ * out the plugins that are async.
+ * https://github.com/cssnano/cssnano/blob/master/packages/cssnano-preset-default/src/index.js
+ *
+ * We may switch back to cssnano if/when they decide to go back to a synchronous API:
+ * https://github.com/cssnano/cssnano/issues/68
+ */
```
Comment (apapko) [inline packages/@lwc/style-compiler/src/postcss-minify-plugins.ts]: thank you for the comment!
