### PR TITLE
fix(engine-core): mismatch with light DOM scoped CSS host token during hydration

### LINKED ISSUE #3008: Scoped CSS host token is not correctly applied to deep light DOM children
When in Light DOM mode, the host token is not always applied to children correctly. This results in a hydration mismatch and issues with rendering.

This is illustrated as a failing test in 0844073a5c2925589525fa57f9a44ed3ff1a52a6.

### PR DESCRIPTION
**Pull request by jmsjtu**
## Details
Closes #3008

During hydration, the scoped CSS-style token is not correctly accounted for when validating CSS class attributes for nested light DOM elements.

There are two scenarios when validation is incorrect:

1.  The host token is not accounted for on nested light DOM elements causing a hydration mismatch.

For example:

x-app.html

```
<template lwc:render-mode="light">
    <x-child class="slds-hello"></x-child>
</template>
```

x-app.scoped.css

```
:host {
  padding: 0;
}

.slds-hello {
  color: blue;
}
```

x-child.html

```
<template lwc:render-mode="light">
</template>
```

x-child.scoped.css

```
:host {
  padding: 8px;
}
```

Generates

```
<x-app class="x-app_app-host">
  <x-child class="x-app_app slds-hello x-child_child-host"></x-child>
</x-app>
```

In the above example, the `x-child_child-host` class is not accounted for during validation and causes a hydration mismatch.

2.  The scoped and host tokens are not accounted for when there are no classes present on the element.

Re-using the above example and removing `.slds-hello`:

x-app.html

```
<template lwc:render-mode="light">
    <x-child></x-child>
</template>
```

Generates

```
<x-app class="x-app_app-host">
  <x-child class="x-app_app x-child_child-host"></x-child>
</x-app>
```

The validation is ignored entirely here because `<x-child>` does not contain dynamic or static classes in the template.

## Does this pull request introduce a breaking change?

* ✅ No, it does not introduce a breaking change.

## Does this pull request introduce an observable change?

* ⚠️ Yes, it does include an observable change.

This is a bug fix and shouldn't break any existing functionality.

## GUS work item
W-11609061

### CODE REVIEW

File: packages/@lwc/engine-core/src/framework/stylesheet.ts [hunk 1]
```diff
@@ -199,6 +200,17 @@ export function getScopeTokenClass(owner: VM): string | null {
...
 }
 
+/**
+ * This function returns the host style token for a custom element if it
+ * exists. Otherwise it returns an empty string.
+ */
+export function getStylesheetTokenHost(vnode: VCustomElement): string {
+    const {
+        template: { stylesheetToken },
+    } = getComponentInternalDef(vnode.ctor);
```
Comment (jmsjtu) [inline packages/@lwc/engine-core/src/framework/stylesheet.ts:210]: The `stylesheetToken` is stored on the template object which lives in the VM.  

Since the VM has not been created yet this was the only way I could think of to get the token.

File: packages/@lwc/engine-core/src/framework/hydration.ts [hunk 2]
```diff
@@ -423,12 +425,15 @@ function validateClassAttr(vnode: VBaseElement, elm: Element, renderer: Renderer
...
-            className = `${scopedToken} ${className}`;
+            className = `${scopedToken} ${className} ${stylesheetTokenHost}`.trim();
         } else if (!isUndefined(classMap)) {
             classMap = {
                 ...classMap,
                 [scopedToken]: true,
+                ...(stylesheetTokenHost && { [stylesheetTokenHost]: true }),
             };
+        } else {
+            className = `${scopedToken} ${stylesheetTokenHost}`.trim();
```
Comment (jmsjtu) [inline packages/@lwc/engine-core/src/framework/hydration.ts:436]: This is to account for the scenario when no class attributes are listed on the element.

File: packages/@lwc/engine-core/src/framework/hydration.ts [hunk 3]
```diff
@@ -423,12 +425,15 @@ function validateClassAttr(vnode: VBaseElement, elm: Element, renderer: Renderer
     // are rendered during SSR. This needs to be accounted for when validating.
     if (scopedToken) {
         if (!isUndefined(className)) {
-            className = `${scopedToken} ${className}`;
+            className = `${scopedToken} ${className} ${stylesheetTokenHost}`.trim();
```
Comment (nolanlawson) [inline packages/@lwc/engine-core/src/framework/hydration.ts:428]: Why the extra `trim()` here? Is it safe to assume whitespace is trimmed in all cases (e.g. static vs non-static nodes)?

File: packages/@lwc/engine-core/src/framework/hydration.ts [hunk 4]
```diff
@@ -423,12 +425,15 @@ function validateClassAttr(vnode: VBaseElement, elm: Element, renderer: Renderer
...
         } else if (!isUndefined(classMap)) {
             classMap = {
                 ...classMap,
                 [scopedToken]: true,
+                ...(stylesheetTokenHost && { [stylesheetTokenHost]: true }),
```
Comment (nolanlawson) [inline packages/@lwc/engine-core/src/framework/hydration.ts:433]: Historically we'd do `isUndefined` here although we're very inconsistent about it
```suggestion
                ...(!isUndefined(stylesheetTokenHost) && { [stylesheetTokenHost]: true }),
```

File: packages/@lwc/engine-core/src/framework/hydration.ts (hunk 2 above)
Comment (nolanlawson) [reply packages/@lwc/engine-core/src/framework/hydration.ts:436]: Same question about `trim` here.

File: packages/@lwc/engine-core/src/framework/stylesheet.ts [hunk 5]
```diff
@@ -199,6 +200,17 @@ export function getScopeTokenClass(owner: VM): string | null {
...
+    return stylesheetToken ? makeHostToken(stylesheetToken) : '';
```
Comment (nolanlawson) [inline packages/@lwc/engine-core/src/framework/stylesheet.ts:211]:
```suggestion
    return !isUndefined(stylesheetToken) ? makeHostToken(stylesheetToken) : '';
```

**Review by nolanlawson — COMMENTED** [review]
This LGTM, although I don't feel confident enough in the hydration code to give an explicit +1.

File: packages/@lwc/engine-core/src/framework/hydration.ts (hunk 3 above)
Comment (jmsjtu) [reply packages/@lwc/engine-core/src/framework/hydration.ts:428]: My thought was that if `stylesheetTokenHost` isn't present then `className` would have an extra space at the end of it.

So the final output would look like "x-main_main slds-hello ".

But now that you mention it, I'm not sure if `scopedToken` or `className` are guaranteed to have spaces already trimmed.

It may be a better idea to conditionally check if `stylesheetToken` exists and append it if it does instead.

File: packages/@lwc/engine-core/src/framework/stylesheet.ts (hunk 1 above)
Comment (divmain) [reply packages/@lwc/engine-core/src/framework/stylesheet.ts:210]: This seems pretty reasonable to me. As we discussed, an alternative would be to add the `stylesheetToken` to each VNode at the time of its creation. But that introduces a second source of truth for `stylesheetToken`, so I like how you've done it here.

**Review by divmain — APPROVED** [review]
This looks great! Minor feedback, no need for re-review.
