### PR TITLE
fix(babel-plugin-component): skip unnecessary registerDecorators (BREAKING CHANGE)

### LINKED ISSUE #2701: [JS compiler] remove registerDecorators for non-LightningElement classes
### Description

The `@lwc/babel-plugin-component` generates `registerDecorators` even for non-LightningElement classes.

#### Steps to Reproduce

https://webcomponents.dev/edit/MYuFA04EubKHITYFNgQm

Input:

```js
class NotALightningElement {
  foo = 'foo'
}
```

Output:

```js
class NotALightningElement {
  constructor() {
    this.foo = 'foo';
  }
}

registerDecorators(NotALightningElement, {
  fields: ["foo"]
});
```

**Possible Solution**

Potentially we can detect a `class` without an `extends` (superclass) and avoid doing `registerDecorators` on that class.

### PR DESCRIPTION
**Pull request by nolanlawson**
## Details

Fixes #2701. New version of #2741

In API version 60+, `registerDecorators` is no longer called for classes that do not extend a superclass (and thus cannot possibly be `LightningElement` classes).

## Does this pull request introduce a breaking change?

* 🚨 Yes, it does introduce a breaking change.

Previously, the following would _not_ be a syntax error:

```js
class MyCustomClass {
  @track foo = 'foo';
}
```

In v60+, this will be a syntax error. The decorators `@track`, `@wire`, and `@api` can only be used on `LightningElement` classes. In the above case, `MyCustomClass` does not `extend` another class, so it cannot possibly be a `LightningElement` class. The fix is to remove the unnecessary `@track`, `@wire`, and `@api` decorators.

## Does this pull request introduce an observable change?

* ⚠️ Yes, it does include an observable change.

See above.

## GUS work item
W-10736098

### CODE REVIEW

**Review by divmain — COMMENTED** [review]
Diffs in test fixtures appear to mostly be tangential to functional changes you've made. If there's a test that needs 👀 , please call that out explicitly.

File: packages/@lwc/babel-plugin-component/src/__tests__/fixtures/decorators/unnecessary-register-decorators/latest/should-register-decorators-for-anonymous-class-that-extends-non-lightning-element/actual.js [hunk 1]
```diff
@@ -0,0 +1,8 @@
+import { api } from "lwc";
+import MyCoolMixin from './mixin.js'
+
+const foo = class extends MyCoolMixin {
```
Comment (divmain) [inline packages/@lwc/babel-plugin-component/src/__tests__/fixtures/decorators/unnecessary-register-decorators/latest/should-register-decorators-for-anonymous-class-that-extends-non-lightning-element/actual.js:4]: Do you only fail when it doesn't extend anything, since it couldn't possibly be extending `LightningElement` indirectly?

File: packages/@lwc/babel-plugin-component/src/decorators/index.ts [hunk 2]
```diff
@@ -270,6 +271,20 @@ function decorators({ types: t }: BabelAPI): Visitor<LwcBabelPluginPass> {
...
+                node.superClass === null &&
+                isAPIFeatureEnabled(
+                    APIFeature.SKIP_UNNECESSARY_REGISTER_DECORATORS,
+                    getAPIVersionFromNumber(state.opts.apiVersion)
+                )
+            ) {
+                // Any class exposing a field *must* extend either LightningElement or some other superclass.
+                // Even in the case of superclasses and mixins that expose fields, those must extend something as well.
+                // So we can skip classes without a superclass to avoid adding unnecessary registerDecorators calls.
+                // However, we only do this in later API versions to avoid a breaking change.
```
Comment (divmain) [inline packages/@lwc/babel-plugin-component/src/decorators/index.ts:284]: Helpful comment, thank you.

File: packages/@lwc/shared/src/api-version.ts [hunk 3]
```diff
@@ -10,15 +10,20 @@ import { isNumber } from './language';
 export const enum APIVersion {
     V58_244_SUMMER_23 = 58,
     V59_246_WINTER_24 = 59,
+    V60_248_SPRING_24 = 60,
```
Comment (divmain) [inline packages/@lwc/shared/src/api-version.ts:13]: Minor nit: Since we're going to be seeing more of these, it'd be nice to have them introduced in a separate PR to keep commit history clean & PRs more readable.

**Review by divmain — APPROVED** [review]
This looks really good to me.

File: packages/@lwc/babel-plugin-component/src/__tests__/fixtures/decorators/unnecessary-register-decorators/latest/should-register-decorators-for-anonymous-class-that-extends-non-lightning-element/actual.js (hunk 1 above)
Comment (nolanlawson) [reply packages/@lwc/babel-plugin-component/src/__tests__/fixtures/decorators/unnecessary-register-decorators/latest/should-register-decorators-for-anonymous-class-that-extends-non-lightning-element/actual.js:4]: Exactly. `extends` is a sniff for "might be a LightningElement."

File: packages/@lwc/shared/src/api-version.ts (hunk 3 above)
Comment (nolanlawson) [reply packages/@lwc/shared/src/api-version.ts:13]: Fair enough. I avoided it since it was like 3 lines though, and since I knew I would have to deal with conflicts anyway once I merged everything all together.
