### PR TITLE
fix(ssr): only default-exported classes are LWC components @W-17312358@

### LINKED ISSUE #4938: SSR compiler interprets all classes with superclasses as LWC components
### Description

Any code which has `SomeClass extends SuperClass` is identified as an LWC component by the SSR compiler.

```js
// stripped down version of LWR's implementation of the NavigationMixin

const Navigate = Symbol('Navigate');
const GenerateUrl = Symbol('GenerateUrl');

function NavigationMixin<TBase extends Constructor>(Base: TBase): TBase {
    invariant(typeof Base.prototype.dispatchEvent === 'function', messages.INVALID_MIXIN_CMP, [Base.toString()]);
    class Mixin extends Base {
        [Navigate](pageRef: PageReference, replace?: boolean, options?: NavigateOptions): void { /* do stuff */  }
        async [GenerateUrl](pageRef: PageReference, options?: NavigateOptions): Promise<string | null> { /* do stuff */ }
    }
    return Mixin;
}

NavigationMixin.Navigate = Navigate;
NavigationMixin.GenerateUrl = GenerateUrl;
export { NavigationMixin };
```

The `class Mixin extends Base` causes the SSR compiler to create an invalid `generateMarkup`, where `Mixin` is not defined -> the compiled code cannot be loaded/executed.

#### Expected Results

No error is throw; SSR compiled code can be executed.

#### Actual Results

`ClassName is not defined`

### Browsers Affected

Node.js

### Version

-   LWC: 18.10.1

**Possible Solution**

The `babel-plugin-component` only considers `export default class` with an `extends` to be an "LWC component". The `@lwc/ssr-compiler` should work the same way.

### PR DESCRIPTION
**Pull request by wjhsf**
## Details

Fixes #4938.

## Does this pull request introduce a breaking change?

-   😮‍💨 No, it does not introduce a breaking change.
-   💔 Yes, it does introduce a breaking change.

## Does this pull request introduce an observable change?

-   🤞 No, it does not introduce an observable change.
-   🔬 Yes, it does include an observable change.

### CODE REVIEW

File: packages/@lwc/engine-server/src/__tests__/fixtures/export-default-component/modules/x/cmp/cmp.js [hunk 1]
```diff
@@ -0,0 +1,4 @@
+import { LightningElement } from 'lwc';
+
+class Component extends LightningElement {}
+export default Component;
```
Comment (nolanlawson) [inline packages/@lwc/engine-server/src/__tests__/fixtures/export-default-component/modules/x/cmp/cmp.js:4]: Could you please add a test case for `export { Component as default }` as well? This is the one that doesn't work currently: https://github.com/salesforce/lwc/issues/4020

File: packages/@lwc/engine-server/src/__tests__/fixtures/export-default-component/modules/x/cmp/cmp.html [hunk 2]
```diff
@@ -0,0 +1,2 @@
+<template>
+</template>
```
Comment (nolanlawson) [inline packages/@lwc/engine-server/src/__tests__/fixtures/export-default-component/modules/x/cmp/cmp.html:2]:
```suggestion
<template>
  yolo
</template>
```

Putting something inside of here actually susses out the difference between `export default Component` and `export { Component as default }`. Without it, we just render an empty `<template shadowrootmode="open">` (probably due to the default `.html` file).

File: packages/@lwc/ssr-compiler/src/compile-js/index.ts [hunk 3]
```diff
@@ -47,16 +47,23 @@ const visitors: Visitors = {
...
+                    ?.references.some((ref) => is.exportDefaultDeclaration(ref.parent)))
+        ) {
+            // If it's a default-exported class with a superclass, then it's an LWC component!
+            state.isLWC = true;
+            if (node.id) {
+                state.lwcClassName = node.id.name;
+            } else {
+                node.id = b.identifier('DefaultComponentName');
+                state.lwcClassName = 'DefaultComponentName';
+            }
```
Comment (nolanlawson) [inline packages/@lwc/ssr-compiler/src/compile-js/index.ts:66]: There is actually a lot of logic that the babel-plugin-component currently does to try to distinguish `LightningElement` classes from non-LE classes:

https://github.com/salesforce/lwc/blob/fb163f7e3c555f093f9c17b4f70446a96ee11662/packages/%40lwc/babel-plugin-component/src/component.ts#L38-L45

https://github.com/salesforce/lwc/blob/fb163f7e3c555f093f9c17b4f70446a96ee11662/packages/%40lwc/babel-plugin-component/src/decorators/index.ts#L289-L295

The first controls `registerComponent` – if a component is not registered, then we'll throw an exception at runtime.

The second controls whether decorators are transformed.

I guess at the end of the day we only have to be 1-to-1 compatible if 1) a compiler error is not going to be thrown somewhere, and 2) the `ssr-compiler` is stricter than the pre-existing toolchain. (#<span></span>1 is because, on core, components will be compiled both for SSR and CSR, so if CSR throws then we are fine.)

So I  guess I am saying this is fine, but we will probably keep discovering edge cases as we go.

File: packages/@lwc/engine-server/src/__tests__/fixtures/superclass/not-superclass/modules/x/mixinSuperclass/mixinSuperclass.js [hunk 4]
```diff
@@ -0,0 +1,7 @@
+export const FancyMixin = Class => {
+    return class extends Class {
```
Comment (wjhsf) [inline packages/@lwc/engine-server/src/__tests__/fixtures/superclass/not-superclass/modules/x/mixinSuperclass/mixinSuperclass.js:2]: TODO: What happens if this mixin has decorated props?

**Review by nolanlawson — APPROVED** [review]

File: packages/@lwc/engine-server/src/__tests__/fixtures/superclass/not-superclass/modules/x/mixinSuperclass/mixinSuperclass.js (hunk 4 above)
Comment (cardoso) [reply packages/@lwc/engine-server/src/__tests__/fixtures/superclass/not-superclass/modules/x/mixinSuperclass/mixinSuperclass.js:2]: I actually do that in production 😆
