### PR TITLE
fix: log compiler warning on duplicate slots

### LINKED ISSUE #1734: Discrepancy between native and synthetic shadow when slotting content
### Description

Given multiple slots with the same name, slotted content for that name should only be rendered under the first slot. LWC renders slotted content under each slot.

#### Expected Results

https://jsbin.com/hiruxewuvu/edit?html,output

#### Actual Results

https://developer.salesforce.com/docs/component-library/tools/playground/0xHlB1Cd/1/edit

### Browsers Affected

All browsers

### Version

- LWC: 1.3.1

### PR DESCRIPTION
**Pull request by nolanlawson**
## Details

Fixes #1734

If a template contains multiple slots with the same name (or multiple default slots), the compiler should emit a warning. The template is invalid in that case, since there's no real reason to have duplicates.

This also fixes a discrepancy between how synthetic and native shadow DOM deal with duplicate slots (#1734, #2351).

## Does this PR introduce breaking changes?

* ✅  `No, it does not introduce breaking changes.`

Any existing template with duplicate slots, when running in synthetic shadow mode, will currently (and incorrectly) render the slotted content multiple times. After this change, those same templates will log a compile-time warning.

## GUS work item

W-7255094

### CODE REVIEW

File: packages/@lwc/errors/src/compiler/error-info/template-transform.ts [hunk 1]
```diff
@@ -506,4 +506,10 @@ export const ParserDiagnostics = {
         level: DiagnosticLevel.Error,
         url: '',
     },
+    NO_DUPLICATE_SLOTS: {
+        code: 1136,
+        message: 'Slot with name "{0}" cannot be duplicated in the same template',
```
Comment (nolanlawson) [inline packages/@lwc/errors/src/compiler/error-info/template-transform.ts:511]: I would love to throw a better error message here for default slots (something like `Default slot cannot be duplicated` rather than `Slot with name "" cannot be duplicated`), but I can't see any way to do that without duplicating the error itself. (Ironic?)

Comment (pmdartus) [reply packages/@lwc/errors/src/compiler/error-info/template-transform.ts:511]: I think it's possible to reuse the same error code.

```js
{
    message: "Invalid duplicate slot ({0}) in the template."
}
```

```js
const info  = name === "" ? "default" : `name="${name}"`;
return warnOnElement(ParserDiagnostics.NO_DUPLICATE_SLOTS, element.__original, [info]);
```

Comment (nolanlawson) [reply packages/@lwc/errors/src/compiler/error-info/template-transform.ts:511]: Ah OK, I wasn't sure if it was okay to put English strings directly into `template-transform.ts`. I'll do this.

File: packages/@lwc/errors/src/compiler/error-info/template-transform.ts [hunk 2]
```diff
@@ -506,4 +506,10 @@ export const ParserDiagnostics = {
         level: DiagnosticLevel.Error,
         url: '',
     },
+    NO_DUPLICATE_SLOTS: {
+        code: 1136,
```
[the remark this answers is not in the document]
Comment (nolanlawson) [reply packages/@lwc/errors/src/compiler/error-info/template-transform.ts:510]: There is already a test for error code uniqueness:

https://github.com/salesforce/lwc/blob/d93e2963d8d32b138ce9ed130d98e7bef84b3d74/packages/%40lwc/errors/src/__tests__/errors.spec.ts#L69-L77

We can add a test for the other part though.

**Comment by caridy** [comment]
For this kind of changes, you will need to get @reiniergs' input, getting the static analysis result to try to identify existent occurrences of this duplication in components today.

File: packages/@lwc/errors/src/compiler/error-info/template-transform.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (nolanlawson) [reply packages/@lwc/errors/src/compiler/error-info/template-transform.ts:510]: https://github.com/salesforce/lwc/pull/2373

**Review by pmdartus — APPROVED** [review]

**Comment by nolanlawson** [comment]
@reiniergs Any pointers on where we could get this information?

**Comment by reiniergs** [comment]
@caridy do you want to count existent occurrences on components in CORE, or DB components as well ?? I can help quickly with CORE, for DB components @nolanlawson need to open a ticket in GUS https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008dPLGIA2/view

**Comment by nolanlawson** [comment]
@reiniergs Maybe we can start with CORE, and then look into DB components if necessary? Hopefully this is such a weird edge-case that nobody is actually using it. If we come up with zero components in CORE (or almost zero), then I think we can safely roll it out without checking DB components. Happy to defer to @caridy on this though.

**Comment by ekashida** [comment]
IMHO, checking DB components is the priority here.

**Comment by pmdartus** [comment]
@nolanlawson To unblock this PR what do you think about changing the diagnostic severity from an error to a warning?

**Comment by nolanlawson** [comment]
Updated so it's just a warning, not an error.

**Review by pmdartus — APPROVED** [review]
