### PR TITLE
fix(synthetic-shadow): apply iframe-content-window polyfill only in IE11

### LINKED ISSUE #1513: Apply iframe-content-window polyfill only in compat mode
### Description
Wrapping the iframe-content-window polyfill results in identity discontinuity issues. So the wrapping should be limited to compat mode only, where it is required.

#### Steps to Reproduce
One example of identity discontinuity issue
https://playground.lwcjs.org/projects/Ik9K8AYHu/1/edit

### PR DESCRIPTION
**Pull request by nolanlawson**
## Details

Fixes #1513

## Does this pull request introduce a breaking change?

* ✅ No, it does not introduce a breaking change.

## Does this pull request introduce an observable change?

* ⚠️ Yes, it does include an observable change.

Non-IE11 browsers will no longer get this iframe polyfill.

## GUS work item
W-12067861

### CODE REVIEW

File: packages/@lwc/synthetic-shadow/src/polyfills/iframe-content-window/detect.ts [hunk 1]
```diff
@@ -4,7 +4,14 @@
...
+
 export default function detect(): boolean {
     // Note: when using this in mobile apps, we might have a DOM that does not support iframes.
-    return typeof HTMLIFrameElement !== 'undefined';
+    const hasIframe = typeof HTMLIFrameElement !== 'undefined';
+
+    // Detect IE, via https://stackoverflow.com/a/9851769
+    const isIE11 = !isUndefined((document as any).documentMode);
+
+    return hasIframe && isIE11;
```
Comment (nolanlawson) [inline packages/@lwc/synthetic-shadow/src/polyfills/iframe-content-window/detect.ts:16]: Unfortunately there is no way (I can think of) to determine with 100% accuracy that we're running in compat mode.

And it would be prohibitively difficult IMO to detect all our compat browsers (Chrome <56, Firefox <63, Safari <11). The feature detection would be different for each one: [Chrome](https://caniuse.com/?compare=chrome+55,chrome+56&compareCats=all), [Firefox](https://caniuse.com/?compare=firefox+52,firefox+53&compareCats=all), [Safari](https://caniuse.com/?compare=safari+10.1,safari+11&compareCats=all).

So I believe we should keep it simple and just detect IE11. Note we have a similar detection elsewhere:

https://github.com/salesforce/lwc/blob/60c352ea4ce349f0078c2e3be43f6e7cd152e8e1/packages/@lwc/engine-dom/src/styles.ts#L27

**Review by divmain — APPROVED** [review]

File: packages/@lwc/synthetic-shadow/src/polyfills/iframe-content-window/detect.ts (hunk 1 above)
Comment (pmdartus) [reply packages/@lwc/synthetic-shadow/src/polyfills/iframe-content-window/detect.ts:16]: This has to be confirmed but I think you can check if you are running in compat mode, if `Proxy.isCompat === true`.

Comment (nolanlawson) [reply packages/@lwc/synthetic-shadow/src/polyfills/iframe-content-window/detect.ts:16]: You're right, `Proxy.isCompat` works. I'll use that.

**Review by pmdartus — APPROVED** [review]

**Comment by jdalton** [comment]
Is this a candidate for 240-patch?
