### PR TITLE
fix(hot-swaps): fix leak in development mode

### LINKED ISSUE #3361: Dev mode leaks components due to synthetic lifecycle and HMR
Basically, sometimes the `vm` added to a `Set` here:

https://github.com/salesforce/lwc/blob/ec2fdfc1826c13390152bfaf2e74886d8e89ff64/packages/%40lwc/engine-core/src/framework/hot-swaps.ts#L166

Is not actually cleaned up here:

https://github.com/salesforce/lwc/blob/ec2fdfc1826c13390152bfaf2e74886d8e89ff64/packages/%40lwc/engine-core/src/framework/hot-swaps.ts#L196-L197

Note this `Set` is part of a mapping of stylesheet functions (which are permanent) to component VMs (which are transient and should be GC'ed).

Incidentally [this commit](https://github.com/salesforce/lwc/pull/3101) revealed the bug in envs where HMR was previously disabled. HMR must be enabled (in dev mode) to repro the leak.

The root cause is actually #3198, because our synthetic lifecycle hooks are not always smart enough to detect when an element is removed from the DOM.

I have a repro (#3362) but not a fix yet.

### PR DESCRIPTION
**Pull request by nolanlawson**
## Details

Fixes #3361

This fixes a memory leak that only occurs in dev mode. There are two parts to this PR:

1. Add integration tests that check for memory leaks in dev mode. This requires Chrome running locally and [wdio DevTools Service](https://webdriver.io/docs/devtools-service/), so I switched our integration tests running in Chrome from Sauce Labs to local.
2. Fix the bug. To do so, I used [the new `WeakRef`/`FinalizationRegistry` API](https://github.com/tc39/proposal-weakrefs), because it seemed most suited to this task. Rather than rely on our own synthetic `disconnectedCallback` lifecycle events to do the cleanup (which is buggy, since it's synthetic), we can just rely on the browser's built-in GC for cleanup.

Note that, currently, the code this is touching (Hot Module Reloading) is only used in LWR. it's not used in LEX, or even in our StackBlitz playground. And of course, it's only used in dev mode.

## Does this pull request introduce a breaking change?

* ✅ No, it does not introduce a breaking change.

## Does this pull request introduce an observable change?

* ✅ No, it does not introduce an observable change.

## GUS work item
[W-12593824](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001LnRLvYAN/view)

### CODE REVIEW

File: packages/@lwc/engine-core/src/framework/vm.ts [hunk 1]
```diff
@@ -256,10 +255,6 @@ function resetComponentStateWhenRemoved(vm: VM) {
         runChildNodesDisconnectedCallback(vm);
         runLightChildNodesDisconnectedCallback(vm);
     }
-
-    if (process.env.NODE_ENV !== 'production') {
-        removeActiveVM(vm);
-    }
```
Comment (nolanlawson) [inline packages/@lwc/engine-core/src/framework/vm.ts:262]: `removeActiveVM` is no longer needed because we're just relying on the browser's built-in GC for cleanup.

File: packages/@lwc/integration-tests/src/components/memory-leaks/test-component-leak/integration/component-leak/component-leak.js [hunk 2]
```diff
@@ -0,0 +1,13 @@
...
+import Child from '../child/child.js';
+
+export default class extends LightningElement {
+    addChild() {
+        this.refs.container.appendChild(createElement('integration-child', { is: Child }));
+    }
+
+    removeChildren() {
+        // Our monkey-patching for synthetic lifecycle events covers removeChild, but not innerHTML = ''
+        this.refs.container.innerHTML = '';
```
Comment (nolanlawson) [inline packages/@lwc/integration-tests/src/components/memory-leaks/test-component-leak/integration/component-leak/component-leak.js:11]: This is the core of the bug here. If we were using native lifecycle hooks, we wouldn't have this problem.

File: .circleci/config.yml [hunk 3]
```diff
@@ -282,15 +289,23 @@ jobs:
...
 
   test_integration:
-    executor: node
-    environment:
-      SAUCE_TUNNEL_ID: lwc_<< pipeline.id	>>_test_integration
+    executor: node-browsers
     steps:
+      - browser-tools/install-browser-tools
       - load_workspace
-      - start_sauce_connect
```
Comment (jye-sf) [inline .circleci/config.yml:290]: I missed the details during the PR review chat but it would be good to document here why no sauce_labs, considering the other two `test_integration_*` jobs do use it.

File: .circleci/config.yml [hunk 4]
```diff
@@ -376,6 +397,14 @@ workflows:
             - test_unit
             - test_karma
 
+      - test_integration_dev:
+          context: lwc-sauce-labs
```
Comment (jye-sf) [inline .circleci/config.yml:401]: Why is the `lwc-sauce-labs` context is needed here when `test_integration_dev` doesn't use it?

File: packages/@lwc/engine-core/src/framework/weak-multimap.ts [hunk 5]
```diff
@@ -0,0 +1,103 @@
+/*
```
Comment (jye-sf) [inline packages/@lwc/engine-core/src/framework/weak-multimap.ts:1]: I'm not asking for it to be done in this PR, but I'm wondering whether the `engine-core/src/framework` folder is due for reorganizing into smaller sub-folders, grouped by functions/sub-modules. Was thinking this file would go great in a `utils/` folder.

File: packages/@lwc/integration-tests/src/components/memory-leaks/test-component-leak/integration/component-leak/component-leak.js [hunk 6]
```diff
@@ -0,0 +1,13 @@
+import { LightningElement, createElement } from 'lwc';
```
[the remark this answers is not in the document]
Comment (nolanlawson) [reply packages/@lwc/integration-tests/src/components/memory-leaks/test-component-leak/integration/component-leak/component-leak.js:1]: You're right, good point. Will rename.

File: .circleci/config.yml (hunk 4 above)
Comment (nolanlawson) [reply .circleci/config.yml]: Fixed!

File: packages/@lwc/engine-core/src/framework/weak-multimap.ts (hunk 5 above)
Comment (nolanlawson) [reply packages/@lwc/engine-core/src/framework/weak-multimap.ts:1]: Yes it has become a hodgepodge!

**Review by jye-sf — APPROVED** [review]

File: packages/@lwc/engine-core/src/framework/weak-multimap.ts [hunk 7]
```diff
@@ -0,0 +1,110 @@
...
+        weakRefs.push(new WeakRef<V>(value));
+
+        // It's important here not to leak the second argument, which is the "held value." The FinalizationRegistry
+        // effectively creates a strong reference between the first argument (the "target") and the held value. When
+        // the target is GC'ed, the callback is called, and then the held value is GC'ed.
+        // Putting the key here would mean the key is not GC'ed until the value is GC'ed, which defeats the purpose
+        // of the WeakMap. Whereas putting the weakRefs array here is fine, because it doesn't have a strong reference
+        // to anything. See also this example:
+        // https://gist.github.com/nolanlawson/79a3d36e8e6cc25c5048bb17c1795aea
+        this._registry.register(value, weakRefs);
```
Comment (nolanlawson) [inline packages/@lwc/engine-core/src/framework/weak-multimap.ts:103]: Realized I had a bug in the weakmap, although it doesn't really matter because the keys were never GC'ed anyway... but it's fixed now.
