### PR TITLE
fix(engine-core): use class name when invoking toString() on component

### LINKED ISSUE #1033: LightningElement.toString always returns undefined
### Description

The LWC class compiler strips the component class name during the transformation. When invoking `toString` on the component instance it returns `[object undefined]` instead of `[object Test]`.

```js
export default class Test extends LightningElement {
	connectedCallback() {
		console.log(`${this}`);
		// [object undefined]
	}
}
```

### Version
- LWC: 0.35.5

### PR DESCRIPTION
**Pull request by ekashida**
## Details

Fixes #1033 by implementing the proposed fix in #1496.

## Does this PR introduce breaking changes?

* ✅ `No, it does not introduce breaking changes.`

## GUS work item

W-7111501

### CODE REVIEW

File: packages/@lwc/engine-core/src/framework/component.ts [hunk 1]
```diff
@@ -44,6 +44,9 @@ export function registerComponent(
     Ctor: ComponentConstructor,
     { name, tmpl: template }: { name: string; tmpl: Template }
```
Comment (pmdartus) [inline packages/@lwc/engine-core/src/framework/component.ts:45]: Based on the types, `name` can't be undefined. The type definition needs to be realigned.

File: packages/@lwc/engine-core/src/framework/component.ts [hunk 2]
```diff
@@ -42,8 +42,11 @@ const signedComponentToMetaMap: Map<ComponentConstructor, ComponentMeta> = new M
  */
 export function registerComponent(
     Ctor: ComponentConstructor,
-    { name, tmpl: template }: { name: string; tmpl: Template }
+    { name, tmpl: template }: { name: string | undefined; tmpl: Template }
 ): ComponentConstructor {
+    if (isUndefined(name)) {
```
Comment (caridy) [inline packages/@lwc/engine-core/src/framework/component.ts:47]: any particular reason for the compiler to provide an undefined name?

Comment (pmdartus) [reply packages/@lwc/engine-core/src/framework/component.ts:47]: It has never been passed as far as I can tell: https://github.com/salesforce/lwc/blob/20275fc44b04e025ae10a2a142bf984c0c0f4f52/packages/%40lwc/babel-plugin-component/src/post-process/transform.js#L117-L120.

At best the compiler will be able to set the `name` as `Ctor.name`. IMO we should remove the optional `name` and just retrieve it from the `Ctor.name`.

File: packages/integration-karma/test/component/LightningElement.toString/index.spec.js [hunk 3]
```diff
@@ -3,14 +3,12 @@ import { createElement } from 'lwc';
...
     const elm = createElement('x-named', { is: Named });
     expect(elm.getToString()).toBe('[object MyFancyComponent]');
 });
 
-// TODO [#1033]: open issue return "[object ]" on Safari
-xit('should fallback to BaseLightningElement if constructor has no name', () => {
+it('should fallback to BaseLightningElementConstructor if constructor has no name', () => {
     const elm = createElement('x-anonymous', { is: Anonymous });
-    expect(elm.getToString()).toBe('[object BaseLightningElement]');
+    expect(elm.getToString()).toBe('[object BaseLightningElementConstructor]');
```
Comment (ekashida) [inline packages/integration-karma/test/component/LightningElement.toString/index.spec.js:13]: Not sure what to do here, the `this` value of a component is different in compat mode so `String(this)` returns `_class`.

File: packages/@lwc/engine-core/src/framework/def.ts [hunk 4]
```diff
@@ -237,16 +230,7 @@ export function getComponentInternalDef(Ctor: unknown, name?: string): Component
             );
         }
 
-        let meta = getComponentRegisteredMeta(Ctor);
-        if (isUndefined(meta)) {
-            // TODO [#1295]: remove this workaround after refactoring tests
```
Comment (ekashida) [inline packages/@lwc/engine-core/src/framework/def.ts:242]: Thanks again, @ravijayaramappa!

**Comment by ekashida** [comment]
@pmdartus @caridy ready for another pass

File: packages/integration-karma/test/component/LightningElement.toString/index.spec.js [hunk 5]
```diff
@@ -3,14 +3,14 @@ import { createElement } from 'lwc';
...
     expect(elm.getToString()).toBe('[object MyFancyComponent]');
 });
 
-// TODO [#1033]: open issue return "[object ]" on Safari
-xit('should fallback to BaseLightningElement if constructor has no name', () => {
-    const elm = createElement('x-anonymous', { is: Anonymous });
-    expect(elm.getToString()).toBe('[object BaseLightningElement]');
-});
+if (process.env.COMPAT !== true) {
+    it('should fallback to BaseLightningElementConstructor if constructor has no name', () => {
```
Comment (ekashida) [inline packages/integration-karma/test/component/LightningElement.toString/index.spec.js:12]: The constructor name ends up as `_class` in compat mode. This seems fine, given that it's no worse than the `undefined` that we render today.

File: packages/@lwc/engine-core/src/framework/component.ts (hunk 2 above)
Comment (caridy) [reply packages/@lwc/engine-core/src/framework/component.ts]: I agreed with that assessment because the compiler can't take it out of the Ctor, because it might be circular, and who knows what other quirk in platform. I'm ok with the runtime inference here.

File: packages/integration-karma/test/component/LightningElement.toString/index.spec.js (hunk 5 above)
Comment (caridy) [reply packages/integration-karma/test/component/LightningElement.toString/index.spec.js:12]: I'm ok with that. Who cares about compat :)?

File: packages/@lwc/engine-core/src/framework/def.ts [hunk 6]
```diff
@@ -237,16 +230,7 @@ export function getComponentInternalDef(Ctor: unknown, name?: string): Component
...
-            meta = {
-                template: undefined,
-                name: Ctor.name,
-            };
-        }
-
-        def = createComponentDef(Ctor, meta, name || Ctor.name);
+        def = createComponentDef(Ctor, name || Ctor.name);
```
Comment (caridy) [inline packages/@lwc/engine-core/src/framework/def.ts:233]: why do we need the second argument? if we are going to do that in createComponentDef?

File: packages/@lwc/engine-core/src/framework/def.ts [hunk 7]
```diff
@@ -96,11 +91,9 @@ function getCtorProto(Ctor: any, subclassComponentName: string): ComponentConstr
 
 function createComponentDef(
     Ctor: ComponentConstructor,
-    meta: ComponentMeta,
     subclassComponentName: string
```
Comment (caridy) [inline packages/@lwc/engine-core/src/framework/def.ts:94]: what is the purpose of subclassComponentName at this point?

Comment (ekashida) [reply packages/@lwc/engine-core/src/framework/def.ts]: Looks like we were just passing around so that it could be used in some error logs inside `getCtorProto()`. I went ahead and removed all that!

File: packages/@lwc/engine-core/src/framework/def.ts [hunk 8]
```diff
@@ -68,11 +63,11 @@ export interface ComponentDef {
 
 const CtorToDefMap: WeakMap<any, ComponentDef> = new WeakMap();
 
-function getCtorProto(Ctor: any, subclassComponentName: string): ComponentConstructor {
+function getCtorProto(Ctor: any): ComponentConstructor {
```
Comment (pmdartus) [inline packages/@lwc/engine-core/src/framework/def.ts:66]:
```suggestion
function getCtorProto(Ctor: ComponentConstructor): ComponentConstructor {
```

File: packages/@lwc/engine-core/src/framework/def.ts [hunk 9]
```diff
@@ -130,10 +118,10 @@ function createComponentDef(
         errorCallback,
         render,
     } = proto;
-    const superProto = getCtorProto(Ctor, subclassComponentName);
+    const superProto = getCtorProto(Ctor);
     const superDef: ComponentDef =
         (superProto as any) !== BaseLightningElement
```
Comment (pmdartus) [inline packages/@lwc/engine-core/src/framework/def.ts:123]:
```suggestion
    const superDef =
        superProto !== BaseLightningElement
```

File: packages/@lwc/engine-core/src/framework/def.ts [hunk 10]
```diff
@@ -130,10 +118,10 @@ function createComponentDef(
...
-            ? getComponentInternalDef(superProto, subclassComponentName)
+            ? getComponentInternalDef(superProto)
             : lightingElementDef;
     const SuperBridge = isNull(superDef) ? BaseBridgeElement : superDef.bridge;
```
Comment (pmdartus) [inline packages/@lwc/engine-core/src/framework/def.ts:126]: Based on the types, `superDef` can't be null here anymore.

```suggestion
    const SuperBridge = superDef.bridge;
```
