### PR TITLE
fix(hydration): fix hydrating SVG classes

### LINKED ISSUE #3429: Hydration fails for <svg> elements
### Description

In SSR, hydrating an` <svg> `element fails with a class mismatch error
`Error: [LWC error]: Mismatch hydrating element <svg>: attribute "class" has different values, expected "" but found "[object SVGAnimatedString]"`

#### Steps to Reproduce
1. Include an `<svg>` element in the component template (adding a class attribute value is not required)
2. Load the page and open the chrome console
3. The following error will show: `Error: [LWC error]: Mismatch hydrating element <svg>: attribute "class" has different values, expected "" but found "[object SVGAnimatedString]"`

See [this demo](https://stackblitz.com/edit/salesforce-lwc-x9zgb4?file=src%2Fmodules%2Fx%2Fchild%2Fchild.html) for a reproduction

```html
<template>
  <svg>
    <circle cx="50" cy="50" r="40" />
  </svg> 
</template>
```

#### Expected Results
`<svg>` element is hydrated without errors

#### Actual Results
`Error: [LWC error]: Mismatch hydrating element <svg>: attribute "class" has different values, expected "" but found "[object SVGAnimatedString]"`

### Browsers Affected
- Chrome
- Safari
- Edge
- Firefox

### Version

- LWC: 2.40.1

**Possible Solution**
The class attribute value of the <svg> element is SVGAnimatedString instead of a string. May require modifying the way the class value is accessed for this case, as the class string value is contained within SVGAnimatedString for the `<svg>` element.

**Additional context/Screenshots**
image

### PR DESCRIPTION
**Pull request by nolanlawson**
## Details

Fixes #3429

## Does this pull request introduce a breaking change?

* ✅ No, it does not introduce a breaking change.

## Does this pull request introduce an observable change?

* ✅ No, it does not introduce an observable change.

## GUS work item
W-12778050

### CODE REVIEW

File: packages/@lwc/engine-core/src/framework/hydration.ts [hunk 1]
```diff
@@ -505,7 +505,12 @@ function validateClassAttr(vnode: VBaseElement, elm: Element, renderer: Renderer
     let nodesAreCompatible = true;
     let readableVnodeClassname;
 
-    const elmClassName = getProperty(elm, 'className');
+    const rawElmClassName: string | SVGAnimatedString = getProperty(elm, 'className');
+
+    // In <svg>s, the `class` attribute becomes an SVGAnimatedString
+    const elmClassName =
+        rawElmClassName instanceof SVGAnimatedString ? rawElmClassName.baseVal : rawElmClassName;
```
Comment (nolanlawson) [inline packages/@lwc/engine-core/src/framework/hydration.ts:512]: [SVGAnimatedString](https://developer.mozilla.org/en-US/docs/Web/API/SVGAnimatedString) is not supported in IE, but neither is hydration.

File: packages/@lwc/engine-core/src/framework/hydration.ts [hunk 2]
```diff
@@ -505,11 +505,12 @@ function validateClassAttr(vnode: VBaseElement, elm: Element, renderer: Renderer
     let nodesAreCompatible = true;
     let readableVnodeClassname;
 
-    const elmClassName = getProperty(elm, 'className');
-    if (!isUndefined(className) && String(className) !== elmClassName) {
+    const elmClassName = getAttribute(elm, 'class');
```
Comment (nolanlawson) [inline packages/@lwc/engine-core/src/framework/hydration.ts:508]: I realized the main problem is using `elm.className` rather than `elm.getAttribute('class')`. The latter gives more consistent results than the former (since SVGs behave differently than HTML).

File: packages/@lwc/engine-core/src/framework/hydration.ts [hunk 3]
```diff
@@ -505,11 +505,12 @@ function validateClassAttr(vnode: VBaseElement, elm: Element, renderer: Renderer
...
     let readableVnodeClassname;
 
-    const elmClassName = getProperty(elm, 'className');
+    const elmClassName = getAttribute(elm, 'class');
+
     if (!isUndefined(className) && String(className) !== elmClassName) {
         // className is used when class is bound to an expr.
         nodesAreCompatible = false;
-        readableVnodeClassname = className;
+        readableVnodeClassname = JSON.stringify(className);
```
Comment (ravijayaramappa) [inline packages/@lwc/engine-core/src/framework/hydration.ts:513]: `data.className` is typed as `string`. Can you add a comment here to say why `JSON.stringify` is used?

File: packages/@lwc/engine-core/src/framework/hydration.ts [hunk 4]
```diff
@@ -523,15 +524,15 @@ function validateClassAttr(vnode: VBaseElement, elm: Element, renderer: Renderer
...
 
         if (classList.length > keys(classMap).length) {
             nodesAreCompatible = false;
         }
-    } else if (isUndefined(className) && elmClassName !== '') {
+    } else if (isUndefined(className) && !isNull(elmClassName)) {
         // SSR contains a className but client-side VDOM does not
         nodesAreCompatible = false;
-        readableVnodeClassname = '';
+        readableVnodeClassname = '""';
```
Comment (ravijayaramappa) [inline packages/@lwc/engine-core/src/framework/hydration.ts:535]: Existing error message:
`attribute "class" has different values, expected "" but found`
New error message:
`attribute "class" has different values, expected """" but found`

File: packages/@lwc/integration-karma/test-hydration/mismatches/class-attr/dynamic-empty-in-ssr-null-string-in-client/index.spec.js [hunk 5]
```diff
@@ -0,0 +1,31 @@
...
+    test(target, snapshots, consoleCalls) {
+        const p = target.shadowRoot.querySelector('p');
+
+        expect(p).not.toBe(snapshots.p);
+        expect(p.className).not.toBe(snapshots.className);
+
+        expect(consoleCalls.warn).toHaveSize(0);
+        expect(consoleCalls.error).toHaveSize(2);
+        expect(consoleCalls.error[0][0].message).toContain(
+            'Mismatch hydrating element <p>: attribute "class" has different values, expected "null" but found null'
```
Comment (ravijayaramappa) [inline packages/@lwc/integration-karma/test-hydration/mismatches/class-attr/dynamic-empty-in-ssr-null-string-in-client/index.spec.js:27]: At first this error message was a bit confusing but I think I got it. It says the client side was expecting the string `'null'` but server side set nothing.

**Review by ravijayaramappa — APPROVED** [review]

File: packages/@lwc/engine-core/src/framework/hydration.ts (hunk 4 above)
Comment (nolanlawson) [reply packages/@lwc/engine-core/src/framework/hydration.ts:537]: I don't think that is the case. `readableVnodeClassname` is passed directly into the logged string:

https://github.com/salesforce/lwc/blob/ff8e24ca765c3d5de6812d4039b7eb75785f3adc/packages/%40lwc/engine-core/src/framework/hydration.ts#L540-L548

In fact, there is a test that covers this case. Note it says `""`, not `""""`:

https://github.com/salesforce/lwc/blob/ff8e24ca765c3d5de6812d4039b7eb75785f3adc/packages/%40lwc/integration-karma/test-hydration/mismatches/class-attr/only-present-in-ssr/index.spec.js#L14-L16

File: packages/@lwc/integration-karma/test-hydration/mismatches/class-attr/dynamic-empty-in-ssr-null-string-in-client/index.spec.js (hunk 5 above)
Comment (nolanlawson) [reply packages/@lwc/integration-karma/test-hydration/mismatches/class-attr/dynamic-empty-in-ssr-null-string-in-client/index.spec.js:27]: Correct. And I think this one would be difficult to clarify further. The server will effectively send `null` in cases of both missing attributes and empty strings, so we don't really know which one the user was using.

File: packages/@lwc/engine-core/src/framework/hydration.ts (hunk 4 above)
Comment (ravijayaramappa) [reply packages/@lwc/engine-core/src/framework/hydration.ts:537]: Ah you are right. I was testing with the template literal in master branch and not your feature branch.

**Review by ravijayaramappa — APPROVED** [review]
