### PR TITLE
fix(template-compiler): exclude comments from static parts when `lwc:preserve-comments` is disabled

### LINKED ISSUE #3933: HTML comments leads to invalid events/refs on static content
Having HTML comments in your template, within static content, combined with either `on*` event listeners or `lwc:ref`, can result in a dev-only error:

    Assert Violation: Should have found all parts by now. Found 1, needed 2

In prod mode, this can result in either `addEventListener` failing or `this.refs.*` failing due to the element not being found (e.g. `Cannot read properties of undefined (reading 'addEventListener')`).

[Minimal repro](https://stackblitz.com/edit/salesforce-lwc-ldpayy?file=src%2Fmodules%2Fx%2Fapp%2Fapp.html,src%2Fmodules%2Fx%2Fapp%2Fapp.js&title=LWC%20playground):

```html
<template>
    <div>
        <!-- comment -->
        <button onclick={onClick}>foo</button>
        <!-- comment -->
        <button onclick={onClick}>bar</button>
    </div>
</template>
```

As a workaround, you can enable `lwc:preserve-comments`:

```patch
-<template>
+<template lwc:preserve-comments>
     <div>
         <!-- comment -->
         <button onclick={onClick}>foo</button>
         <!-- comment -->
         <button onclick={onClick}>bar</button>
     </div>
</template>
```

...or remove the comments:

```patch
<template>
     <div>
-        <!-- comment -->
         <button onclick={onClick}>foo</button>
-        <!-- comment -->
         <button onclick={onClick}>bar</button>
     </div>
</template>
```

This bug was introduced by https://github.com/salesforce/lwc/pull/3694 (landed in OSS v3.7.0, release 248 aka Spring '24).

### PR DESCRIPTION
**Pull request by jmsjtu**
## Details

Fixes #3933.

The first commit (de9a1278ddd882792830f624800042a32412e542) contains the fix.

## Does this pull request introduce a breaking change?

* ✅ No, it does not introduce a breaking change.

## Does this pull request introduce an observable change?

* ⚠️ Yes, it does include an observable change.

Fixes a bug where comments are being included as part of static parts when `lwc:preserve-comments` is disabled. This causes a mismatch in the partsId between the compiler and runtime.

The error that is thrown for this bug will be removed.

## GUS work item
W-14786540

### CODE REVIEW

File: packages/@lwc/template-compiler/src/codegen/codegen.ts [hunk 1]
```diff
@@ -578,7 +583,14 @@ export default class CodeGen {
...
         while (stack.length > 0) {
             const node = stack.shift()!;
-            partId++;
+
+            if (!(isComment(node) && !this.preserveComments)) {
+                // Skip adding part index for comments when preserveComments is disabled.
+                // The partId represents the nodes in the DOM tree at runtime, comments will be
+                // stripped out when preserveComments is disabled.
+                partId++;
+            }
```
Comment (jmsjtu) [inline packages/@lwc/template-compiler/src/codegen/codegen.ts:592]: Exclude comments from the `partId` count when `lwc:preserve-comments` is disabled as they will be stripped out at runtime.

File: packages/@lwc/integration-karma/test/static-content/index.spec.js [hunk 2]
```diff
@@ -396,3 +398,45 @@ describe('event listeners on deep paths', () => {
         }
     });
 });
+
+describe('comments', () => {
```
Comment (ekashida) [inline packages/@lwc/integration-karma/test/static-content/index.spec.js:402]: Not sure if this top-level `describe` adds value. We can remove it in favor of top-level `it` if you agree.

File: packages/@lwc/integration-karma/test/static-content/index.spec.js [hunk 3]
```diff
@@ -396,3 +398,45 @@ describe('event listeners on deep paths', () => {
...
+        document.body.appendChild(elm);
+
+        await Promise.resolve();
+
+        const { foo, bar } = extractDataIds(elm);
+        const refs = elm.getRefs();
+
+        foo.click();
+        expect(elm.fooWasClicked).toBe(true);
+        expect(refs.foo).not.toBeFalsy();
```
Comment (ekashida) [inline packages/@lwc/integration-karma/test/static-content/index.spec.js:416]:
```suggestion
        expect(refs.foo).toBe(foo);
```

File: packages/@lwc/integration-karma/test/static-content/index.spec.js [hunk 4]
```diff
@@ -396,3 +398,45 @@ describe('event listeners on deep paths', () => {
...
+
+        bar.click();
+        expect(elm.barWasClicked).toBe(true);
+        expect(refs.bar).not.toBeFalsy();
```
Comment (ekashida) [inline packages/@lwc/integration-karma/test/static-content/index.spec.js:420]:
```suggestion
        expect(refs.bar).toBe(bar);
```

File: packages/@lwc/integration-karma/test/static-content/index.spec.js [hunk 5]
```diff
@@ -396,3 +398,45 @@ describe('event listeners on deep paths', () => {
...
+        document.body.appendChild(elm);
+
+        await Promise.resolve();
+
+        const { foo, bar } = extractDataIds(elm);
+        const refs = elm.getRefs();
+
+        foo.click();
+        expect(elm.fooWasClicked).toBe(true);
+        expect(refs.foo).not.toBeFalsy();
```
Comment (ekashida) [inline packages/@lwc/integration-karma/test/static-content/index.spec.js:436]:
```suggestion
        expect(refs.foo).toBe(foo);
```

File: packages/@lwc/integration-karma/test/static-content/index.spec.js [hunk 6]
```diff
@@ -396,3 +398,45 @@ describe('event listeners on deep paths', () => {
...
+
+        bar.click();
+        expect(elm.barWasClicked).toBe(true);
+        expect(refs.bar).not.toBeFalsy();
```
Comment (ekashida) [inline packages/@lwc/integration-karma/test/static-content/index.spec.js:440]:
```suggestion
        expect(refs.bar).toBe(bar);
```

**Review by ekashida — APPROVED** [review]
Minor suggestions

File: packages/@lwc/integration-karma/test/static-content/index.spec.js (hunk 3 above)
Comment (jmsjtu) [reply packages/@lwc/integration-karma/test/static-content/index.spec.js:416]: nice!

File: packages/@lwc/integration-karma/test/static-content/index.spec.js (hunk 2 above)
Comment (jmsjtu) [reply packages/@lwc/integration-karma/test/static-content/index.spec.js]: @ekashida I added a more [descriptive text](https://github.com/salesforce/lwc/pull/3934/files#diff-c1197d00755cf941e7a000d5b59dad82bcf7e4133c7445dd7e792893a6f7a49aR402) for the test but kept it in a `describe` block to keep it in line with what we're doing with the rest of the tests in this file.

File: packages/@lwc/template-compiler/src/codegen/codegen.ts [hunk 7]
```diff
@@ -578,7 +583,14 @@ export default class CodeGen {
         // Depth-first traversal. We assign a partId to each element, which is an integer based on traversal order.
         while (stack.length > 0) {
             const node = stack.shift()!;
-            partId++;
+
+            if (!(isComment(node) && !this.preserveComments)) {
```
Comment (ravijayaramappa) [inline packages/@lwc/template-compiler/src/codegen/codegen.ts:587]: This is easier to read :)
```suggestion
            // Skip comment nodes in parts count, as they will be stripped in production, unless when `preseveComments` is enabled
            if (!isComment(node) || this.preserveComments)) {
```

**Review by nolanlawson — APPROVED** [review]

**Review by ravijayaramappa — APPROVED** [review]
