### PR TITLE
fix: invalid wire decorator type definition post wire reform

### LINKED ISSUE #2026: Invalid wire decorator type definition post wire reform
### Description

The current `@wire` decorator type definition is outdated and doesn't reflect the changes made with wire reform.

#### Steps to Reproduce

Live example: [codesandbox](https://codesandbox.io/s/wire-adapter-type-mismatch-kru41?file=/src/index.ts)

```ts
import { LightningElement, wire } from 'lwc';

class WireAdapter {
  constructor(cb: any) {}
}

export default class extends LightningElement {
  @wire(WireAdapter)
  field;
}
```

#### Expected Results

tsc should not report an error.

#### Actual Results

```
Argument of type 'typeof WireAdapter' is not assignable to parameter of type '(config?: any) => any'.
  Type 'typeof WireAdapter' provides no match for the signature '(config?: any): any'.ts(2345)
```

### Version
- LWC: 1.8.0

### Possible Solution

The types exported out of the [`lwc`](https://github.com/salesforce/lwc/blob/master/packages/lwc/types.d.ts#L182) package should match the one used internally in [`@lwc/engine-core`](https://github.com/salesforce/lwc/blob/master/packages/@lwc/engine-core/src/framework/wiring.ts#L266-L270).

### PR DESCRIPTION
**Pull request by jodarove**
## Details
Fixes #2026

## Does this PR introduce breaking changes?

* ✅ `No, it does not introduce breaking changes.`

### CODE REVIEW

File: packages/lwc/types.d.ts [hunk 1]
```diff
@@ -193,8 +193,12 @@ declare module 'lwc' {
      * @param getType imperative accessor for the data source
      * @param config configuration object for the accessor
      */
-    export function wire(getType: (config?: any) => any, config?: any): PropertyDecorator;
+    export function wire(
+        getType: WireAdapterConstructor | LegacyWireAdapterConstructor,
```
Comment (pmdartus) [inline packages/lwc/types.d.ts:197]:
```suggestion
        adapter: WireAdapterConstructor | LegacyWireAdapterConstructor,
```

File: packages/lwc/types.d.ts [hunk 2]
```diff
@@ -193,8 +193,12 @@ declare module 'lwc' {
      * @param getType imperative accessor for the data source
      * @param config configuration object for the accessor
```
Comment (pmdartus) [inline packages/lwc/types.d.ts:194]:
```suggestion
     * @param adapter the adapter used to provision data
     * @param config configuration object for the adapter
```

**Review by pmdartus — APPROVED** [review]
