### PR TITLE
fix(template-compiler): support exportparts attribute

### LINKED ISSUE #3005: exportparts attribute on a shadow host throws error
### Description

When using the `::part` API with native shadow, in particular part forwarding through `exportparts`, the LWC engine throws an error:

`Unknown public property "exportparts" of element <PRIMITIVE-OVERLAY>. This is likely a typo on the corresponding attribute "exportparts".`

Reflecting the attribute on the host gets around this error and I can export the part up the shadow boundary.
#### Steps to Reproduce

```html
<!-- parent -->
<template>
  <div part="dropdown">
    <a href="" part="label"></a>
    <primitive-overlay exportparts="overlay">
      <slot></slot>
    </primitive-overlay>
  </div>
</template>
```
```html
<!--child-->
<template>
  <div part="overlay" role="none">
    <slot></slot>
  </div>
</template>
```

#### Expected Results
No error is throw, standard API usage

#### Actual Results
`Unknown public property "exportparts" of element <PRIMITIVE-OVERLAY>. This is likely a typo on the corresponding attribute "exportparts".`

### Browsers Affected
N/A

### Version
- LWC: 2.20.1

@gonzalocordero @nolanlawson

### PR DESCRIPTION
**Pull request by nolanlawson**
## Details

Fixes #3005

Adds support for the [`exportparts`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/exportparts) attribute.

## Does this pull request introduce a breaking change?

* ✅ No, it does not introduce a breaking change.

## Does this pull request introduce an observable change?

* ⚠️ Yes, it does include an observable change.

You can use `exportparts` now without it throwing an error.

## GUS work item

W-11605544

### CODE REVIEW

File: packages/@lwc/template-compiler/src/parser/attribute.ts [hunk 1]
```diff
@@ -200,6 +200,9 @@ export function isAttribute(element: BaseElement, attrName: string): boolean {
             attrName === 'class' ||
             attrName === 'key' ||
             attrName === 'slot' ||
+            // `exportparts` is only valid on a shadow host, and only available as an attribute, not a property
```
Comment (ekashida) [inline packages/@lwc/template-compiler/src/parser/attribute.ts:203]:
```suggestion
            // `exportparts` is a global attribute that can be used on any element but only has an effect on shadow hosts. There is no corresponding property that reflects to this attribute.
```

**Review by ekashida — APPROVED** [review]
I got a little confused because `exportpart` was already listed as a global attribute. I guess `isAttribute()` should probably have been named `shouldRenderAsAttribute()` instead.

**Review by pmdartus — APPROVED** [review]
