### PR TITLE
fix(synthetic-shadow): Fix API interaction with light DOM components

### LINKED ISSUE #2386: Slot assignedElements and assignedNodes returns incorrect value with light DOM and synthetic shadow
### Description

The returned value from `HTMLSlotElement.protype.assignedNode` and `HTMLSlotElement.protype.assignedElements` is incorrect when invoked on a shadow DOM slot with slotted content from a light DOM component.

#### Steps to Reproduce

Karma test: [branch](https://github.com/salesforce/lwc/compare/pmdartus/light-dom-assigned-elements)

```html
<!-- x-light-consumer -->
<template lwc:render-mode="light">
    <x-shadow-container>
        <p>Hello from Light DOM</p>
    </x-shadow-container>
</template>
```

```html
<!-- x-shadow-container -->
<template>
    <slot></slot>
</template>
```

#### Expected Results
When invoking `assignedNodes` on the `<slot>` the return value should be an array containing `<p>` element.

#### Actual Results
Instead, the returned value is an empty array when synthetic shadow is enabled.

### Browsers Affected
All

### Version
- LWC: 2.2.4

### PR DESCRIPTION
**Pull request by pmdartus**
## Details

This PR fixes incorrect behavior when light DOM components are used with synthetic shadow DOM:
- `HTMLSlotElement.prototype.assignedNodes` and `HTMLSlotElement.prototype.assignedElements` on shadow slots and light DOM slotted content.
- `Node.prototype.parentNode` and `Node.prototype.parentElenent` on light DOM slotted content inside a shadow DOM component.

Fix #2386 

## Does this PR introduce breaking changes?

* ✅ `No, it does not introduce breaking changes.`

## The PR fulfills these requirements:
* Have tests for the proposed changes been added? ✅ 
* Have you followed [these instructions](../CONTRIBUTING.md#-commit-message-conventions) to clearly describe the issue being fixed or feature enhanced? ✅

### CODE REVIEW

File: packages/@lwc/synthetic-shadow/src/faux-shadow/node.ts [hunk 1]
```diff
@@ -300,7 +300,16 @@ defineProperties(Node.prototype, {
             if (isNodeShadowed(this)) {
                 return parentNodeGetterPatched.call(this);
             }
-            return parentNodeGetter.call(this);
+
+            const parentNode = parentNodeGetter.call(this);
+
+            // Handle the case where a top level light DOM element is slotted into a synthetic
+            // shadow slot.
+            if (!isNull(parentNode) && isSlotElement(parentNode) && isNodeShadowed(parentNode)) {
```
Comment (nolanlawson) [inline packages/@lwc/synthetic-shadow/src/faux-shadow/node.ts:308]:
```suggestion
            if (!isNull(parentNode) && isSyntheticSlotElement(parentNode)) {
```

`isSyntheticSlotElement` does the same thing as `isSlotElement(node) && isNodeShadowed(node)`.

File: packages/@lwc/synthetic-shadow/src/faux-shadow/node.ts [hunk 2]
```diff
@@ -310,7 +319,20 @@ defineProperties(Node.prototype, {
...
-            return parentElementGetter.call(this);
+
+            const parentElement = parentElementGetter.call(this);
+
+            // Handle the case where a top level light DOM element is slotted into a synthetic
+            // shadow slot.
+            if (
+                !isNull(parentElement) &&
+                isSlotElement(parentElement) &&
+                isNodeShadowed(parentElement)
```
Comment (nolanlawson) [inline packages/@lwc/synthetic-shadow/src/faux-shadow/node.ts:330]: Ditto

File: packages/integration-karma/test/light-dom/assigned-node-element/index.spec.js [hunk 3]
```diff
@@ -0,0 +1,110 @@
...
+            expect(Array.from(nodes.slot.childNodes)).toEqual([]);
+        });
+        it('parentNode', () => {
+            expect(nodes.p.parentNode).toEqual(nodes.consumer);
+        });
+        it('parentElement', () => {
+            expect(nodes.p.parentElement).toEqual(nodes.consumer);
+        });
+        xit('getRootNode', () => {
+            expect(nodes.p.getRootNode()).toEqual(document);
```
[the remark this answers is not in the document]
Comment (pmdartus) [reply packages/integration-karma/test/light-dom/assigned-node-element/index.spec.js]: It's a little more complex than this. `Node.prototype.getRootNode` fails when a light DOM element is the top-level light DOM element because there is no owner key to inherit from.

File: packages/integration-karma/test/light-dom/assigned-node-element/index.spec.js [hunk 4]
```diff
@@ -0,0 +1,110 @@
...
+        });
+        it('textContent', () => {
+            expect(nodes.consumer.textContent).toEqual(
+                'I am an assigned element.I am an assigned text.'
+            );
+        });
+        xit('innerHTML', () => {
+            expect(nodes.consumer.innerHTML).toEqual(
```
[the remark this answers is not in the document]
Comment (pmdartus) [reply packages/integration-karma/test/light-dom/assigned-node-element/index.spec.js]: Yes, you are right.

**Comment by pmdartus** [comment]
@ekashida I am not planning to fix the new bugs I uncovered as part of this PR, I created dedicated issues for each bug.
Could you review the slotting changes I made?

**Review by nolanlawson — APPROVED** [review]

**Review by jodarove — APPROVED** [review]
lgtm. just a note: This change may have perf implications. IIRC, in the platform, `.parentNode` is part of the critical path because Aura uses it to render aura components. and `isSlotElement` does `node instanceof HTMLSlotElement`.

File: packages/@lwc/synthetic-shadow/src/faux-shadow/node.ts [hunk 5]
```diff
@@ -300,7 +300,16 @@ defineProperties(Node.prototype, {
             if (isNodeShadowed(this)) {
                 return parentNodeGetterPatched.call(this);
             }
-            return parentNodeGetter.call(this);
+
+            const parentNode = parentNodeGetter.call(this);
+
+            // Handle the case where a top level light DOM element is slotted into a synthetic
+            // shadow slot.
+            if (!isNull(parentNode) && isSyntheticSlotElement(parentNode)) {
```
Comment (jodarove) [inline packages/@lwc/synthetic-shadow/src/faux-shadow/node.ts:308]: When will this be the case? `isSyntheticSlotElement` implementation is as:

```js
export function isSyntheticSlotElement(node: Node): node is HTMLSlotElement {
    return isSlotElement(node) && isNodeShadowed(node);
}
```

but if this line is executed, we know for sure that `isNodeShadowed(node)` is false, therefore `isSyntheticSlotElement` will always return `false`.

**Review by jodarove — CHANGES_REQUESTED** [review]

**Review by jodarove — APPROVED** [review]
(dismiss my previous request for change) This does lgtm. just a note: This change may have perf implications. IIRC, in the platform, `.parentNode` is part of the critical path in the platform because Aura uses it to render aura components. and `isSlotElement` does `node instanceof HTMLSlotElement`.

**Review by ekashida — APPROVED** [review]
lgtm
