### PR TITLE
fix(template-compiler): Handle case when location information is missing

### LINKED ISSUE #2411: [@lwc/template-compiler] Parsing error thrown for table row
### Description

A bug seems to have snuck in between v2.2.5 and v2.2.6. [The repro](https://github.com/nolanlawson/lwc-barebone/commit/664c0fc7dca8573bd22fd54e95ffbbf48dca273b) is pretty minimal:

```html
<template>
  <table>
    <tr></tr>
  </table>
</template>
```

Result:

     Error: Unexpected compilation error: LWC1052: Error parsing attribute: Cannot 
       destructure property 'startTag' of 'node.__location' as it is null.

#### Steps to Reproduce

See repro above

#### Expected Results

No error

#### Actual Results

Parsing error

### Browsers Affected

N/A

### Version

LWC 2.2.6

**Possible Solution**

None

**Additional context/Screenshots**

None

### PR DESCRIPTION
**Pull request by pmdartus**
## Details

When `parse5` autocorrects invalid HTML syntax, new AST nodes are created without location information. This PR addresses this use case when the AST node location is missing.

Fix #2411 

## Does this PR introduce breaking changes?

* ✅ `No, it does not introduce breaking changes.`

## The PR fulfills these requirements:
* Have tests for the proposed changes been added? ✅ 
* Have you followed [these instructions](../CONTRIBUTING.md#-commit-message-conventions) to clearly describe the issue being fixed or feature enhanced? ✅ 

## GUS work item
W-9594350

### CODE REVIEW

File: packages/@lwc/template-compiler/src/parser/index.ts [hunk 1]
```diff
@@ -803,24 +803,32 @@ export default function parse(source: string, state: State): TemplateParseResult
...
-                    messageArgs: [element.tag],
-                    origin: {
-                        location: {
-                            line: startTag.startLine || startTag.line,
-                            column: startTag.startCol || startTag.col,
-                            start: startTag.startOffset,
-                            length: startTag.endOffset - startTag.startOffset,
+        // Check if a non-void element has a matching closing tag.
+        //
+        // With parse5 automatically recovering from invalid HTML some of AST node might not have
```
Comment (ravijayaramappa) [inline packages/@lwc/template-compiler/src/parser/index.ts:808]:
```suggestion
        // With parse5 automatically recovering from invalid HTML, some AST nodes might not have
```

**Review by ravijayaramappa — APPROVED** [review]

**Review by nolanlawson — APPROVED** [review]
