### PR TITLE
fix(engine-core): add abstraction for moving vfragments

### LINKED ISSUE #3377: lwc:if renders out of order with for:each
### Description
When using `lwc:if` in close proximity to a `for:each`, the elements rendered to the DOM load out of order at times.

#### Steps to Reproduce

1. Loop over any iterable
2. Have a conditionally rendered block that may change after the loop
3. Add a value to the iterable and toggle the boolean controlling the `lwc:if`

```
<template for:each={items} for:item="item">
    <div key={item.id}>
        {item.text}
    </div>
</template>
<template lwc:if={items.length}>
    test
</template>
<button onclick={addItem}>add</button>


// JS
counter = 0;
addItem(){
  this.items.push(`${this.counter++}`);
}
```

If you click the button 3 times, you'd expect this to be rendered:

> 0
> 1
> 2
> test

however, you see this instead

> 0
> test
> 1
> 2

[Link to Example](https://stackblitz.com/edit/salesforce-lwc-jgxmh1?file=src%2Fmodules%2Fx%2Fapp%2Fapp.html,src%2Fmodules%2Fx%2Fapp%2Fapp.js&title=LWC%20playground)

** Edit - I haven't had time to test all of the conditions more closely, but I felt this was the most basic example I could provide

### LINKED ISSUE #3396: lwc:if renders conditional elements out of order
### Description

When templated elements with "lwc:if" are rendered after the initial connectedCallback(), they are rendered in reverse order from the template. This only happens if the conditional elements are rendered after the initial connect, using setTimeout in my example but I've also seen it happen after @wire emissions.

As a workaround, this doesn't happen with "if:true" and "if:false". Possibly duplicate of #3377.

#### Steps to Reproduce

Create a component similar to [this stackblitz.com component.](https://stackblitz.com/edit/salesforce-lwc-baqfbv?file=src/modules/x/parent/parent.html) LWC version `2.40.0`

Template

```html
<template>
  <div>
  <div lwc:if={showChildren}>1</div>
  <div lwc:if={showChildren}>2</div>
  <div lwc:if={showChildren}>3</div>
  <div lwc:if={showChildren}>4</div>
  <div lwc:if={showChildren}>5</div>
  </div>
</template>
```

JS

```javascript
import { LightningElement } from 'lwc';

export default class Parent extends LightningElement {
  showChildren = false;

  connectedCallback() {
    setTimeout(() => {
      this.showChildren = true;
    }, 500);
  }
}
```

#### Expected Results

After the component renders, it should display "1 2 3 4 5" on separate lines, matching the HTML template.

#### Actual Results

It actually shows "5 4 3 2 1" on separate lines, in reverse order from expected.

### Browsers Affected

Current Chrome, v110.

### Version

- LWC: 2.40.0
- @lwc/rollup-plugin: 2.40.0

**Additional context/Screenshots**

Screenshot from [stackblitz.com playground](https://stackblitz.com/edit/salesforce-lwc-baqfbv?file=src/modules/x/parent/parent.js).

Screenshot 2023-03-09 at 10 11 49 AM

### PR DESCRIPTION
**Pull request by ekashida**
## Details

Implements an abstraction for moving vfragment-based nodes around and fixes both reported issues around insertion when the vfragment-based nodes are the reference node. Note that we already had logic for mounting/patching/removing.

Fixes #3396
Fixes #3377

## Does this pull request introduce a breaking change?

No

## Does this pull request introduce an observable change?

Yes

## GUS work item

W-12630370

### CODE REVIEW

**Comment by ekashida** [comment]
Downstream repo at [salesforce-experience-platform-emu/lds-lightning-platform](https://github.com/salesforce-experience-platform-emu/lds-lightning-platform) currently has a broken build.

File: packages/@lwc/engine-core/src/framework/rendering.ts [hunk 1]
```diff
@@ -222,7 +222,7 @@ function mountFragment(
     mountVNodes(children, parent, renderer, anchor);
 
     // children of a fragment will always have at least the two delimiters.
-    vnode.elm = children[children.length - 1]!.elm;
+    vnode.elm = children[0]!.elm;
```
Comment (jye-sf) [inline packages/@lwc/engine-core/src/framework/rendering.ts:225]: Do any of the tests exercise the blocks of code starting on line 882 and line 893, for VFragments? I don't fully understand the implications of this change on the dynamic diffing algo, but those blocks might be impacted. Verifying we have tests for those and they still work would help ease my concerns.

Specifically, that `renderer.nextSibling(oldEndVnode.elm!)` makes me think this change will fix inserting before the VFragment but then break inserting after the VFragment.

**Review by jye-sf — CHANGES_REQUESTED** [review]
Requested to add or verify we have tests for a specific use case.

File: packages/@lwc/integration-karma/test/rendering/issue-3377/index.spec.js [hunk 2]
```diff
@@ -0,0 +1,18 @@
...
+        const elm = createElement('x-test', { is: Test });
+        document.body.appendChild(elm);
+
+        elm.addItem();
+        elm.addItem();
+
+        await Promise.resolve();
+
+        const items = elm.shadowRoot.querySelectorAll('.item');
+        expect(items.length).toBe(3);
```
Comment (ravijayaramappa) [inline packages/@lwc/integration-karma/test/rendering/issue-3377/index.spec.js:15]: Assert the order of items in the first for:each block

**Review by mpsenn — APPROVED** [review]

File: packages/@lwc/engine-core/src/framework/rendering.ts [hunk 3]
```diff
@@ -235,7 +241,7 @@ function patchFragment(n1: VFragment, n2: VFragment, parent: ParentNode, rendere
     }
 
     // Note: not reusing n1.elm, because during patching, it may be patched with another text node.
-    n2.elm = children[children.length - 1]!.elm;
+    n2.elm = children[0]!.elm;
```
Comment (ekashida) [inline packages/@lwc/engine-core/src/framework/rendering.ts:244]: We now use the leading text anchor instead, since the other one is accessible via `nextSibling()`.

File: packages/@lwc/engine-core/src/framework/rendering.ts [hunk 4]
```diff
@@ -547,7 +553,20 @@ function insertNode(node: Node, parent: Node, anchor: Node | null, renderer: Ren
...
         unlockDomMutation();
     }
-    renderer.insert(node, parent, anchor);
+
+    // Handle vfragment-based nodes
+    if (leadingFragmentAnchors.has(node)) {
+        // The content of vfragment-based nodes are delimited by leading and trailing anchors.
+        const leading = node;
+        const content = renderer.nextSibling(node);
+        const trailing = renderer.nextSibling(content);
```
Comment (nolanlawson) [inline packages/@lwc/engine-core/src/framework/rendering.ts:562]: I don't think it's safe to assume that the `nextSibling` of the `content` is the trailing text node. A fragment could have multiple `content` nodes, e.g.:

```html
<template lwc:If={foo}>
  <div>1</div>
  <div>2</div>
  <div>3</div>
</template>
```

Could you add a test for a fragment containing multiple child nodes like this? ^

File: packages/@lwc/engine-core/src/framework/rendering.ts [hunk 5]
```diff
@@ -882,12 +901,17 @@ function updateDynamicChildren(
...
-            );
+
+            const elm = oldEndVnode.elm!;
+            let nextSibling = renderer.nextSibling(elm);
+            // If this is a leading anchor for a vfragment, then we want to use the node after the
+            // trailing anchor: [..., [leading, content, trailing], nextSibling, ...]
+            if (leadingFragmentAnchors.has(elm)) {
+                const trailing = renderer.nextSibling(nextSibling);
+                nextSibling = renderer.nextSibling(trailing);
+            }
```
Comment (nolanlawson) [inline packages/@lwc/engine-core/src/framework/rendering.ts:912]: Same question as above – this seems to assume that there is only one `content`, when there could be multiple content nodes.

File: packages/@lwc/integration-karma/test/rendering/issue-3396/x/test/test.html [hunk 6]
```diff
@@ -0,0 +1,5 @@
+<template>
+    <div lwc:if={show}>1</div>
```
Comment (nolanlawson) [inline packages/@lwc/integration-karma/test/rendering/issue-3396/x/test/test.html:2]: More than one node inside here should repro any issues with multiple `content` nodes.

**Review by nolanlawson — CHANGES_REQUESTED** [review]
It seems strange to me that the diffing algo would have knowledge of fragment start and end text positions. My understanding is that the goal of fragments was to insert the text nodes and just let the diffing algo act accordingly.

Looking at [how Vue does it](https://github.com/vuejs/core/blob/4c9bfd2b999ce472f7481aae4f9dc5bb9f76628e/packages/runtime-core/src/renderer.ts#L1078-L1092), they seem to insert both the leading and trailing text nodes and then patch the content in before the trailing one. Can we use a similar technique?

File: packages/@lwc/engine-core/src/framework/rendering.ts (hunk 4 above)
Comment (jye-sf) [reply packages/@lwc/engine-core/src/framework/rendering.ts:562]: That's correct. We can't just assume that there's a single content node, so we can't use nextSibling. VFragments are [text, ...content, text] so there can be any number of children.

File: packages/@lwc/engine-core/src/framework/rendering.ts (hunk 3 above)
Comment (jye-sf) [reply packages/@lwc/engine-core/src/framework/rendering.ts:244]: I don't think we can reliably use `nextSibling()` to find the trailing text node. There can be any number of content nodes between `lead` and `trailing`.

**Review by jye-sf — CHANGES_REQUESTED** [review]
https://github.com/salesforce/lwc/pull/3405#issuecomment-1483248116

**Comment by nolanlawson** [comment]
@jye-sf Nice research! Yeah that makes sense to me. If VFragment can't just be "any old VNode," then let's go whole-hog and keep a reference to its start and end anchors explicitly.

File: packages/@lwc/integration-karma/test/rendering/issue-3396/x/test/test.html (hunk 6 above)
Comment (ekashida) [reply packages/@lwc/integration-karma/test/rendering/issue-3396/x/test/test.html:2]: Added this test case to `sequential-reordering` to keep the test and the submitted repro similar.

File: packages/@lwc/engine-core/src/framework/rendering.ts [hunk 7]
```diff
@@ -543,6 +541,31 @@ function updateTextContent(vnode: VText | VComment, renderer: RendererAPI) {
...
+
+    const children = vnode.children;
+    const nodesToInsert = [];
+    for (let i = 0; i < children.length; i += 1) {
+        const child = children[i];
+        if (!isNull(child)) {
+            nodesToInsert.push(child.elm!);
+        }
+    }
+    nodesToInsert.forEach((node) => renderer.insert(node, parent, anchor));
```
Comment (nolanlawson) [inline packages/@lwc/engine-core/src/framework/rendering.ts:562]: Let's use a regular `for` loop here (or the `forEach` from `@lwc/shared`).

File: packages/@lwc/engine-core/src/framework/rendering.ts [hunk 8]
```diff
@@ -925,7 +967,11 @@ function updateDynamicChildren(
 
                         // We've already cloned at least once, so it's no longer read-only
                         (oldCh as any[])[idxInOld] = undefined;
-                        insertNode(elmToMove.elm!, parent, oldStartVnode.elm!, renderer);
+                        if (isVFragment(elmToMove)) {
+                            insertFragment(elmToMove, parent, oldStartVnode.elm!, renderer);
+                        } else {
+                            insertNode(elmToMove.elm!, parent, oldStartVnode.elm!, renderer);
+                        }
```
Comment (nolanlawson) [inline packages/@lwc/engine-core/src/framework/rendering.ts:974]: These five lines are repeated 3 times... Maybe we could add an `insertFragmentOrNode` utility function?

File: packages/@lwc/engine-core/src/framework/rendering.ts (hunk 7 above)
Comment (nolanlawson) [reply packages/@lwc/engine-core/src/framework/rendering.ts]: On second thought, do we even need two separate `for` loops here? We create the array `nodesToInsert` with the first loop, then use the second loop to insert those nodes... So can these two `for` loops be combined to avoid creating the temporary array?

File: packages/@lwc/engine-core/src/framework/rendering.ts [hunk 9]
```diff
@@ -882,18 +905,37 @@ function updateDynamicChildren(
...
-                renderer
-            );
+
+            // In the case of fragments, the `elm` property of a vfragment points to the leading
+            // anchor. To determine the next sibling of the whole fragment, we need to use the
+            // trailing anchor as the argument to nextSibling():
+            // [..., [leading, ...content, trailing], nextSibling, ...]
+            let anchor: Node | null;
+            if (isVFragment(oldEndVnode)) {
+                const trailing = oldEndVnode.children[oldEndVnode.children.length - 1]!.elm!;
```
Comment (nolanlawson) [inline packages/@lwc/engine-core/src/framework/rendering.ts:917]: I think storing the trailing anchor node directly on the `vnode` could be a bit more elegant than implicitly getting it from the last child... but it's not a big deal if it's a pain to refactor.

File: packages/@lwc/engine-core/src/framework/rendering.ts (hunk 8 above)
Comment (ekashida) [reply packages/@lwc/engine-core/src/framework/rendering.ts:976]: If the argument to that function becomes `VFragment | Node` I think I would need to add a new method on the renderer to be able to check if it's an instance of `Node`, or do some duck-typing to see if it's a `vnode`.

File: packages/@lwc/integration-karma/test/rendering/sequential-reordering/index.spec.js [hunk 10]
```diff
@@ -0,0 +1,45 @@
...
+    it('move fragment left (["foo", "fragment"] => ["fragment", "bar"])', async () => {
+        const elm = createElement('x-test', { is: Test });
+        document.body.appendChild(elm);
+        await Promise.resolve();
+
+        // Setup
+        elm.beforeItems = ['foo'];
+        elm.afterItems = [];
+        await Promise.resolve();
+
```
Comment (nolanlawson) [inline packages/@lwc/integration-karma/test/rendering/sequential-reordering/index.spec.js:15]:
```suggestion
        const initialContents = [...elm.shadowRoot.childNodes].map((_) => _.textContent);
        expect(initialContents).toEqual(['', 'foo', '', '', '一', '二', '三', '']);

```

Just for clarity (and out of a bit of paranoia), I think it would be great to assert what the state is before the mutation.

File: packages/@lwc/engine-core/src/framework/rendering.ts (hunk 8 above)
Comment (nolanlawson) [reply packages/@lwc/engine-core/src/framework/rendering.ts:976]: I see. OK, well then it's no big deal.

File: packages/@lwc/engine-core/src/framework/api.ts [hunk 11]
```diff
@@ -90,6 +90,7 @@ function fr(key: Key, children: VNodes, stable: 0 | 1): VFragment {
         children: [t(''), ...children, t('')],
         stable,
         owner: getVMBeingRendered()!,
+        trailingAnchor: undefined,
```
Comment (nolanlawson) [inline packages/@lwc/engine-core/src/framework/api.ts:93]: It seems like we should be able to set the `trailingAnchor` immediately here, since we already have the `t('')` above.

Ditto for `elm` since we already know what the leading anchor is too.

**Comment by ekashida** [comment]
That should be ‘Node | VFragment’

**Comment by nolanlawson** [comment]
> That should be ‘Node | VFragment’

I tested 0a18c805e, and it compiles with TypeScript and passes the Karma tests. It looks like `VNode` (not `Node`) is correct there?

**Comment by ekashida** [comment]
@nolanlawson  Ah, I see what you mean.

File: packages/@lwc/engine-core/src/framework/rendering.ts [hunk 12]
```diff
@@ -543,6 +541,37 @@ function updateTextContent(vnode: VText | VComment, renderer: RendererAPI) {
...
+        const nodesToInsert = [];
+        for (let i = 0; i < children.length; i += 1) {
+            const child = children[i];
+            if (!isNull(child)) {
+                nodesToInsert.push(child.elm!);
+            }
+        }
+        for (let i = 0; i < nodesToInsert.length; i += 1) {
+            renderer.insert(nodesToInsert[i], parent, anchor);
+        }
```
Comment (nolanlawson) [inline packages/@lwc/engine-core/src/framework/rendering.ts:565]: These two `for` loops should be collapsible into one, to avoid creating the temporary `nodesToInsert` array.

File: packages/@lwc/engine-core/src/framework/api.ts [hunk 13]
```diff
@@ -82,14 +82,18 @@ function st(fragment: Element, key: Key): VStatic {
...
         type: VNodeType.Fragment,
         sel: undefined,
         key,
         elm: undefined,
-        children: [t(''), ...children, t('')],
+        children: [leading, ...children, trailing],
         stable,
         owner: getVMBeingRendered()!,
+        leading,
+        trailing,
```
Comment (nolanlawson) [inline packages/@lwc/engine-core/src/framework/api.ts:96]: This is great! I love being explicit here, instead of `elm` implicitly being either leading or trailing. ❤️

**Review by nolanlawson — APPROVED** [review]
One small nitpick, otherwise LGTM!

File: packages/@lwc/engine-core/src/framework/rendering.ts (hunk 12 above)
Comment (ekashida) [reply packages/@lwc/engine-core/src/framework/rendering.ts:565]: Yeah, I had them separated because the `nextSibling()` would be a different value once I inserted the node, but I think I can read the next sibling before inserting in the same loop.

**Review by ravijayaramappa — APPROVED** [review]

**Comment by ekashida** [comment]
@jye-sf another review please!

File: packages/@lwc/engine-core/src/framework/rendering.ts [hunk 14]
```diff
@@ -882,18 +907,25 @@ function updateDynamicChildren(
...
-                renderer.nextSibling(oldEndVnode.elm!),
-                renderer
-            );
+
+            // In the case of fragments, the `elm` property of a vfragment points to the leading
+            // anchor. To determine the next sibling of the whole fragment, we need to use the
+            // trailing anchor as the argument to nextSibling():
+            // [..., [leading, ...content, trailing], nextSibling, ...]
+            let anchor: Node | null;
+            if (isVFragment(oldEndVnode)) {
```
Comment (jye-sf) [inline packages/@lwc/engine-core/src/framework/rendering.ts:916]: Minor nit: we could save a check here if `trailing` was on VNode rather than Vfragment because we can do
```javascript
anchor = renderer.nextSibling(oldEndVnode.trailing ? oldEndVnode.trailing.elm : oldEndVnode.elm)
```
but I don't think we need to hold up this PR for that change. We can consider that when refactoring.

**Review by jye-sf — APPROVED** [review]
