### PR TITLE
fix: fix !important in inline styles

### LINKED ISSUE #2443: `!important` is not preserved in `style` attributes
### Description

```html
<template>
  <div style="color: green !important;">I should be green</div>
</template>
```

The above style (`color: green !important`) is stripped out during compilation, whereas it should be preserved.

#### Steps to Reproduce

- [Live repro](https://webcomponents.dev/edit/hWathLte4ei6Pv1sVmfK)
- [Working example using raw HTML/CSS](https://codepen.io/nolanlawson-the-selector/pen/mdmLGdx)

### Version

- LWC: 2.3.0

**Possible Solution**

Avoid using `!important`. Or alternatively, set the `style` manually in the `renderedCallback`.

**Additional context/Screenshots**

Screen Shot 2021-07-30 at 2 06 22 PM

### PR DESCRIPTION
**Pull request by nolanlawson**
Fixes #2443

## Details

Converts `styleMap` to a `styleDecls` array containing triples of `[name, value, important?]`. E.g.:

```html
<div style="background: blue !important; color: red; opacity: 0.5 !important"></div>
```

becomes:

```js
{
  /* ... */
  styleDecls: [
    ['background', 'blue', true],
    ['color', 'red'],
    ['opacity', '0.5', true]
  ]
}  
```

So the compiler output has changed.

## Does this PR introduce breaking changes?

* ✅ `No, it does not introduce breaking changes.`

## The PR fulfills these requirements:
* Have tests for the proposed changes been added? ✅ 
* Have you followed [these instructions](../CONTRIBUTING.md#-commit-message-conventions) to clearly describe the issue being fixed or feature enhanced? ✅ 

## GUS work item
W-9682301

### CODE REVIEW

File: packages/@lwc/engine-core/src/3rdparty/snabbdom/types.ts [hunk 1]
```diff
@@ -77,7 +77,7 @@ export interface VNodeData {
     className?: any;
     style?: any;
     classMap?: Classes;
-    styleMap?: VNodeStyle;
+    styles?: VNodeStyle;
```
Comment (nolanlawson) [inline packages/@lwc/engine-core/src/3rdparty/snabbdom/types.ts:80]: I'm open to naming this something else, e.g. `styleArray`. It's a bit confusing to have both `style` and `styles`. 

Although whatever we name it, that will literally be the compiled output, because it can't be mangled.

File: packages/@lwc/template-compiler/src/codegen/index.ts [hunk 2]
```diff
@@ -421,15 +421,29 @@ function transform(codeGen: CodeGen): t.Expression {
...
+                    // - string values are parsed and turned into a `styles` array
+                    // containing triples of [name, value, important (optional)]
                     if (value.type === IRAttributeType.Expression) {
                         const styleExpression = bindExpression(value.value, element);
                         data.push(t.property(t.identifier('style'), styleExpression));
                     } else if (value.type === IRAttributeType.String) {
                         const styleMap = parseStyleText(value.value);
-                        const styleObj = objectToAST(styleMap, (key) => t.literal(styleMap[key]));
-                        data.push(t.property(t.identifier('styleMap'), styleObj));
+                        const styles: Array<[string, string] | [string, string, boolean]> =
```
Comment (jye-sf) [inline packages/@lwc/template-compiler/src/codegen/index.ts:431]: Would this be better off as a helper function in `helpers.ts`?

At first I wanted to ask why this wasn't just added to `parseStyleText` from line 430, but I think it still makes sense to keep that functionality separate.

File: packages/@lwc/engine-core/src/3rdparty/snabbdom/types.ts (hunk 1 above)
Comment (abdulsattar) [reply packages/@lwc/engine-core/src/3rdparty/snabbdom/types.ts:80]: `styleDecls`?

**Review by abdulsattar — APPROVED** [review]
LGTM!

File: packages/@lwc/engine-core/src/3rdparty/snabbdom/types.ts [hunk 3]
```diff
@@ -15,7 +15,7 @@
 
 import { VM } from '../../framework/vm';
 
-export type VNodeStyle = Record<string, string>;
+export type VNodeStyle = Array<[string, string] | [string, string, boolean]>;
```
[the remark this answers is not in the document]
Comment (nolanlawson) [reply packages/@lwc/engine-core/src/3rdparty/snabbdom/types.ts:18]: Unfortunately no. TypeScript doesn't seem to understand that it's impossible to have an array of length 3 where the third item is `undefined`. So it leads to errors elsewhere where we would have to force it to understand that the value is not `undefined`.

File: packages/@lwc/template-compiler/src/codegen/index.ts (hunk 2 above)
Comment (nolanlawson) [reply packages/@lwc/template-compiler/src/codegen/index.ts:431]: Done.

File: packages/@lwc/engine-core/src/3rdparty/snabbdom/types.ts (hunk 1 above)
Comment (nolanlawson) [reply packages/@lwc/engine-core/src/3rdparty/snabbdom/types.ts]: Done. I like `styleDecls` as a name.

**Review by jye-sf — APPROVED** [review]

File: packages/@lwc/engine-core/src/3rdparty/snabbdom/types.ts [hunk 4]
```diff
@@ -15,7 +15,7 @@
 
 import { VM } from '../../framework/vm';
 
-export type VNodeStyle = Record<string, string>;
+export type VNodeStyleDecls = Array<[string, string] | [string, string, boolean]>;
```
Comment (ekashida) [inline packages/@lwc/engine-core/src/3rdparty/snabbdom/types.ts:18]: I suggest we set the third value to `false` instead of leaving it `undefined`. This way we can just pass the value as-is when invoking`renderer.setCSSStyleProperty()` later on.
```suggestion
export type VNodeStyleDecls = Array<[string, string, boolean]>;
```

Comment (nolanlawson) [reply packages/@lwc/engine-core/src/3rdparty/snabbdom/types.ts:18]: The reason I avoided this is because I figured most style declarations would not have `!important`, so I didn't want to generate a bunch of `, false`s in the template. Maybe this isn't a big deal though; minify will turn it into `!1` and gzip will dedup it.

Comment (nolanlawson) [reply packages/@lwc/engine-core/src/3rdparty/snabbdom/types.ts]: OK done, it's always an array of length 3 now.

**Review by ekashida — APPROVED** [review]
