### PR TITLE
fix(ssr): remove unused imports

### LINKED ISSUE #4793: [SSR v2] Fix unused imports from `'@lwc/ssr-runtime'`
In core, this Rollup warning is treated as an error:

```
LWC1002: Error in module resolution: "api", "track" and "wire" are imported from external
module "@lwc/ssr-runtime" but never used in `foo.js`
```

This happens because sometimes we are sloppy about doing e.g.:

```js
import { api } from '@lwc/ssr-runtime'
```

... in the output `.js` files from the `@lwc/ssr-compiler`, even though `api` may be unused.

We should clean this up and ensure that all of our imports are actually used.

### PR DESCRIPTION
**Pull request by nolanlawson**
## Details

Fixes #4793.

This solves the Gordion knot by cutting it. I added an extra AST transform to remove unused imports from `@lwc/ssr-runtime`. This means we don't need to manually track any imports during AST generation.

## Does this pull request introduce a breaking change?

-   😮‍💨 No, it does not introduce a breaking change.

## Does this pull request introduce an observable change?

-   🤞 No, it does not introduce an observable change.

### CODE REVIEW

File: packages/@lwc/ssr-compiler/src/compile-template/transformers/element.ts [hunk 1]
```diff
@@ -235,6 +231,8 @@ export const Element: Transformer<IrElement | IrExternalComponent | IrSlot> = fu
         childContent = [];
     }
 
+    cxt.hoist(bImportHtmlEscape(), importHtmlEscapeKey);
+
```
Comment (nolanlawson) [inline packages/@lwc/ssr-compiler/src/compile-template/transformers/element.ts:235]: We can probably simplify our `ctx.hoist()` logic elsewhere as well (since we can basically just import everything from `@lwc/ssr-runtime` once and let the optimizer do its magic) but I've punted on that for now.

**Review by ekashida — APPROVED** [review]

File: packages/@lwc/ssr-compiler/src/optimize-imports.ts [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+        const { node, scope } = path;
+        if (!node || !scope) {
+            return;
+        }
+        if (node.source.type === 'Literal' && node.source.value === '@lwc/ssr-runtime') {
+            node.specifiers = node.specifiers.filter(
+                (specifier) =>
+                    // There shouldn't be any default imports anyway
+                    specifier.type === 'ImportSpecifier' &&
+                    // If there are references, then the import is used
```
Comment (nolanlawson) [inline packages/@lwc/ssr-compiler/src/optimize-imports.ts:26]:
```suggestion
                    // If there are references, then the import is used. Note that an import will _always_
                    // have a binding (of type "module"), but it may not have references.
```
