### PR TITLE
fix: fix light dom slot forwarding bug

### LINKED ISSUE #4446: Light DOM slot forwarding fails to render for duplicated slot names
This is an issue introduced by #4258. It affects light DOM components, and specifically named slots whose slot names are forwarded, and only when those slot names are duplicated in the containing template.

The bug is a bit hard to describe, so it's easier to illustrate with a repro: 5035243e3

The key component here is `header.html`:

```html
<template lwc:render-mode="light">
    <div lwc:if={isTablet}>
        <slot name="navigation"></slot>
    </div>
    <div lwc:else>
        <slot name="navigation"></slot>
    </div>
</template>
```

Note the duplicated slots with the same name (`navigation`). This is the key thing that triggers the bug when slot forwarding is present. If the condition (in this case `isTablet`) is toggled, then the content that should be rendered inside of the `<slot>` is not rendered.

### PR DESCRIPTION
**Pull request by nolanlawson**
## Details

Fixes #4446, partially reverts #4258.

The main thing this PR does is revert us from the 252 behavior to the 250 behavior, while also adding additional code to ensure that `disconnectedCallback` fires correctly. The bulk of what you need to know is in the code comments.

## Does this pull request introduce a breaking change?

-   😮‍💨 No, it does not introduce a breaking change.

## Does this pull request introduce an observable change?

-   🔬 Yes, it does include an observable change.

The ordering of `disconnectedCallback`s firing in light DOM may change when using slot forwarding.

### CODE REVIEW

File: packages/@lwc/engine-core/src/framework/api.ts [hunk 1]
```diff
@@ -273,22 +274,31 @@ function s(
...
+                        // `vmBeingRendered.velements`), but this actually might not trigger disconnectedCallback
+                        // in synthetic lifecycle mode. The reason for this is that a reactivity change may cause
+                        // the slottable component to unmount, but _not_ the slotter component (see issue #4446).
+                        //
+                        // If this occurs, then the slottable component (i.e .this component we are rendering right
+                        // now) is the one that needs to own the clone. Whereas if a reactivity change higher in the
+                        // tree causes the slotter to unmount, then the slottable will also unmount. So using the
+                        // current VM works either way.
+                        if (isVCustomElement(vnode)) {
+                            addVNodeToChildLWC(clonedVNode as VCustomElement);
```
Comment (nolanlawson) [inline packages/@lwc/engine-core/src/framework/api.ts:301]: This is the main change.

File: packages/@lwc/integration-karma/test/light-dom/lifecycle/index.spec.js
Comment (nolanlawson) [inline packages/@lwc/integration-karma/test/light-dom/lifecycle/index.spec.js:1]: Note that the order of `disconnectedCallback`s firing has changed, when light DOM slot forwarding is enabled. I could not managed to get it to fire in exactly the same order as it did before.

I think this not a super-serious observable change – most of the time, `disconnectedCallback` ordering doesn't matter as much as `connectedCallback` ordering. This is because `dC` is mostly used for simple teardowns, whereas `cC` may be used to fire events that should be caught by the container. (`dC` cannot fire events because the element is disconnected from the DOM.)

File: packages/@lwc/integration-karma/test/light-dom/lifecycle/index.spec.js [hunk 2]
```diff
@@ -34,149 +65,192 @@ describe('standard slotting', () => {
...
-                          '9:disconnectedCallback',
-                          '8:disconnectedCallback',
-                      ]
-                    : [
-                          '10:connectedCallback',
-                          '11:connectedCallback',
-                          '12:connectedCallback',
-                          '4:disconnectedCallback',
-                      ]
-            );
```
Comment (nolanlawson) [inline packages/@lwc/integration-karma/test/light-dom/lifecycle/index.spec.js:179]: This is actually a bugfix – we are now correctly firing the expected `disconnectedCallback`s in synthetic lifecycle mode.

File: packages/@lwc/integration-karma/test/light-dom/lifecycle/index.spec.js [hunk 3]
```diff
@@ -34,149 +65,192 @@ describe('standard slotting', () => {
...
+                // remove entire element
+                document.body.removeChild(elm);
+                await Promise.resolve();
+
+                expect(window.timingBuffer).toEqual([
+                    '8:disconnectedCallback',
+                    '9:disconnectedCallback',
+                    '4:disconnectedCallback',
+                ]);
+            });
```
Comment (nolanlawson) [inline packages/@lwc/integration-karma/test/light-dom/lifecycle/index.spec.js:253]: I didn't strictly need to add any `remove entire element` tests here, but I wanted to cover all my bases.

File: packages/@lwc/integration-karma/test/light-dom/lifecycle/index.spec.js
Comment (jmsjtu) [reply packages/@lwc/integration-karma/test/light-dom/lifecycle/index.spec.js:1]: If I remember correctly, the original issue with cloning vnodes was `disconnectedCallback` not firing, so I think it should be fine as long as it's being called.

Comment (nolanlawson) [reply packages/@lwc/integration-karma/test/light-dom/lifecycle/index.spec.js:1]: Yep, this is why I added a test – `should invoke connectedCallback/disconnectedCallback at all`. It's more important that `disconnectedCallback` actually fires than that it fires in a particular order.

**Comment by jmsjtu** [comment]
I think this should also resolve #3731

**Comment by nolanlawson** [comment]
> I think this should also resolve https://github.com/salesforce/lwc/issues/3731

Unfortunately I tested it out, and it looks like the #3731 is still not resolved by this PR. 😞

**Review by ekashida — APPROVED** [review]
🤞
