### PR TITLE
fix(ssr): add `experimentalDynamicComponent` aka dynamic imports

### LINKED ISSUE #5021: [SSR] Support `dynamicImport` config
`engine-server` currently transforms `import()`s into a loader pattern based on the `dynamicImports` config:

https://github.com/salesforce/lwc/blob/318383047982b93a582ed7fa80472b7ba9143d19/packages/%40lwc/babel-plugin-component/src/types.ts#L16-L19

`ssr-compiler` on the other hand turns `import()`s into a no-op because we didn't think we would need to support this. #4887 

As it turns out, LWR supports [async functions in LWC component files](https://developer.salesforce.com/docs/platform/lwr/guide/lwr-enable-ssr-site.html#load-data-during-ssr). So we will need to make `ssr-compiler` behave the same as `engine-server` w.r.t. this config.

### PR DESCRIPTION
**Pull request by nolanlawson**
## Details

Fixes #5021

Related: #5031 #5032

## Does this pull request introduce a breaking change?

- 😮‍💨 No, it does not introduce a breaking change.

## Does this pull request introduce an observable change?

- 🤞 No, it does not introduce an observable change.

### CODE REVIEW

**Review by wjhsf — APPROVED** [review]

File: packages/@lwc/ssr-compiler/src/compile-js/index.ts [hunk 1]
```diff
@@ -33,13 +35,26 @@ const visitors: Visitors = {
...
-        return path.replaceWith(
-            b.callExpression(
-                b.memberExpression(b.identifier('Promise'), b.identifier('resolve')),
-                []
-            )
-        );
+    ImportExpression(path, state) {
+        const { experimentalDynamicComponent, importManager } = state;
+        if (!experimentalDynamicComponent) {
+            return;
```
Comment (nolanlawson) [inline packages/@lwc/ssr-compiler/src/compile-js/index.ts:41]:
```suggestion
            // if no `experimentalDynamicComponent` config, then leave dynamic `import()`s as-is
            return;
```

File: packages/@lwc/ssr-compiler/src/compile-js/index.ts [hunk 2]
```diff
@@ -33,13 +35,27 @@ const visitors: Visitors = {
...
+                // TODO [#5032]: Harmonize errors thrown in `@lwc/ssr-compiler`
+                throw new Error('todo - LWCClassErrors.INVALID_DYNAMIC_IMPORT_SOURCE_STRICT');
+            }
+        }
+        const loader = experimentalDynamicComponent.loader;
+        if (!loader) {
+            return;
+        }
+        const source = path.node!.source!;
+        // 1. insert `import { load as __load } from '${loader}' at top of program
```
Comment (nolanlawson) [inline packages/@lwc/ssr-compiler/src/compile-js/index.ts:55]:
```suggestion
        // 1. insert `import { load as __load } from '${loader}'` at top of program
```

File: packages/@lwc/ssr-compiler/src/compile-js/index.ts [hunk 3]
```diff
@@ -33,13 +35,27 @@ const visitors: Visitors = {
...
+        }
+        if (experimentalDynamicComponent.strictSpecifier) {
+            if (!is.literal(path.node?.source) || typeof path.node.source.value !== 'string') {
+                // TODO [#5032]: Harmonize errors thrown in `@lwc/ssr-compiler`
+                throw new Error('todo - LWCClassErrors.INVALID_DYNAMIC_IMPORT_SOURCE_STRICT');
+            }
+        }
+        const loader = experimentalDynamicComponent.loader;
+        if (!loader) {
+            return;
```
Comment (nolanlawson) [inline packages/@lwc/ssr-compiler/src/compile-js/index.ts:52]:
```suggestion
            // if no `loader` defined, then leave dynamic `import()`s as-is
            return;
```

File: packages/@lwc/ssr-compiler/src/compile-js/index.ts [hunk 4]
```diff
@@ -171,12 +188,21 @@ const visitors: Visitors = {
             path.parentPath.node.arguments = [b.identifier('propsAvailableAtConstruction')];
         }
     },
+    Program: {
+        leave(path, state) {
+            const importDeclarations = state.importManager.getImportDeclarations();
```
Comment (nolanlawson) [inline packages/@lwc/ssr-compiler/src/compile-js/index.ts:193]:
```suggestion
            // After parsing the whole tree, insert needed imports
            const importDeclarations = state.importManager.getImportDeclarations();
```
