### PR TITLE
fix(template-compiler): fix static listeners with deep paths

### LINKED ISSUE #3804: [Template compiler] Event listeners on deep objects not being serialized properly
Consider a component using deep paths to reference an event listener:

```js
export default class App extends LightningElement {
  foo = {
    bar: {
      baz() {
        console.log('yolo')
      }
    }
  }
}
```

```html
<template>
    <button onclick={foo.bar.baz}>click me</button>
</template>
```

This results in:

    Uncaught TypeError: Cannot read properties of undefined (reading 'foo')

Because it's rendered as:

```js
function tmpl($api, $cmp, $slotset, $ctx) {
  const {b: api_bind, st: api_static_fragment} = $api;
  const {_m0, _m1} = $ctx;
  return [api_static_fragment($fragment1(), 1, {
    on: {
      "click": _m1 || ($ctx._m1 = api_bind($cmp.$cmp.foo.bar.baz)) // improper path here
    }
  })];
```

This [repros in 2.46.0](https://stackblitz.com/edit/salesforce-lwc-5f9fam?file=src%2Fmodules%2Fx%2Fapp%2Fapp.html,package.json&title=LWC%20playground) but [not 2.41.4](https://stackblitz.com/edit/salesforce-lwc-2wnunh?file=src%2Fmodules%2Fx%2Fapp%2Fapp.js,package.json&title=LWC%20playground). It was probably introduced by https://github.com/salesforce/lwc/pull/3519 which landed in [2.46.0](https://github.com/salesforce/lwc/releases/tag/v2.46.0).

### PR DESCRIPTION
**Pull request by nolanlawson**
## Details

Fixes #3804

## Does this pull request introduce a breaking change?

* ✅ No, it does not introduce a breaking change.

## Does this pull request introduce an observable change?

* ✅ No, it does not introduce an observable change.

### CODE REVIEW

File: packages/@lwc/template-compiler/src/codegen/codegen.ts [hunk 1]
```diff
@@ -482,6 +489,10 @@ export default class CodeGen {
         }
 
         const scope = this;
+
+        // Cloning here is necessary because `this.replace()` is destructive, and we might use the
+        // node later during static content optimization
+        expression = doStructuredClone(expression);
```
Comment (nolanlawson) [inline packages/@lwc/template-compiler/src/codegen/codegen.ts:495]: This is a really subtle bug – the code below is mutating the AST, which only becomes a problem later if we try to re-use it, which we do during the static content optimization, which is a second pass on top of the first pass we already did.

First pass:

https://github.com/salesforce/lwc/blob/650305a7f0a43d64c7286a39aeb9cd8891e9f283/packages/%40lwc/template-compiler/src/codegen/index.ts#L642

Second pass:

https://github.com/salesforce/lwc/blob/650305a7f0a43d64c7286a39aeb9cd8891e9f283/packages/%40lwc/template-compiler/src/codegen/codegen.ts#L572

File: packages/@lwc/template-compiler/src/codegen/codegen.ts [hunk 2]
```diff
@@ -32,6 +32,13 @@ import { getStaticNodes, memorizeHandler, objectToAST } from './helpers';
 import { serializeStaticElement } from './static-element-serializer';
 import { bindComplexExpression } from './expression';
 
+// structuredClone is only available in Node 17+
+// https://developer.mozilla.org/en-US/docs/Web/API/structuredClone#browser_compatibility
+const doStructuredClone =
+    typeof structuredClone === 'function'
+        ? structuredClone
+        : (obj: any) => JSON.parse(JSON.stringify(obj));
```
Comment (nolanlawson) [inline packages/@lwc/template-compiler/src/codegen/codegen.ts:40]: I manually ran the Karma tests in Node 16 just to be safe.

**Comment by nolanlawson** [comment]
Looks like the AST format changed... will need another look.

**Comment by nolanlawson** [comment]
Found a pre-existing issue: https://github.com/salesforce/lwc/issues/3808

File: packages/@lwc/integration-karma/test/static-content/x/deepListener/deepListener.html [hunk 3]
```diff
@@ -0,0 +1,29 @@
...
+    <!-- 3 levels deep -->
+    <div data-id="static3" onfoo={uno.dos.tres}></div>
+    <div data-id="dynamic3" data-dynamic={dynamic} onfoo={uno.dos.tres}></div>
+    <div>
+        <div data-id="deepStatic3" onfoo={uno.dos.tres}></div>
+    </div>
+
+    <!-- 4 levels deep -->
+    <div data-id="static4" onfoo={ichi.ni.san.yon}></div>
+    <div data-id="dynamic4" data-dynamic={dynamic} onfoo={ichi.ni.san.yon}></div>
```
Comment (ekashida) [inline packages/@lwc/integration-karma/test/static-content/x/deepListener/deepListener.html:25]: When counting up: ichi, ni, san, **shi**, go, roku, **shichi**, hachi, kyu, ju.
When counting down: ju, kyu, hachi, **nana**, roku, go, **yon**, san, ni, ichi.
```suggestion
    <div data-id="dynamic4" data-dynamic={dynamic} onfoo={ichi.ni.san.shi}></div>
```
😆

File: packages/@lwc/integration-karma/test/static-content/x/deepListener/deepListener.js [hunk 4]
```diff
@@ -0,0 +1,33 @@
...
+
+    one() {
+        this.counter++;
+    }
+
+    un = ((component) => ({
+        deux() {
+            component.counter++;
+        },
+    }))(this);
```
Comment (ekashida) [inline packages/@lwc/integration-karma/test/static-content/x/deepListener/deepListener.js:14]:
```suggestion
    un: {
        deux: () => {
            this.counter++;
        },
    };
```

File: packages/@lwc/integration-karma/test/static-content/x/deepListener/deepListener.js [hunk 5]
```diff
@@ -0,0 +1,33 @@
...
+
+    uno = ((component) => ({
+        dos: {
+            tres() {
+                component.counter++;
+            },
+        },
+    }))(this);
```
Comment (ekashida) [inline packages/@lwc/integration-karma/test/static-content/x/deepListener/deepListener.js:22]:
```suggestion
    uno: {
        dos: {
            tres: () => {
                this.counter++;
            },
        },
    };
```

File: packages/@lwc/integration-karma/test/static-content/x/deepListener/deepListener.js [hunk 6]
```diff
@@ -0,0 +1,33 @@
...
+
+    ichi = ((component) => ({
+        ni: {
+            san: {
+                yon() {
+                    component.counter++;
+                },
+            },
+        },
+    }))(this);
```
Comment (ekashida) [inline packages/@lwc/integration-karma/test/static-content/x/deepListener/deepListener.js:32]:
```suggestion
    ichi: {
        ni: {
            san: {
                shi: () => {
                    this.counter++;
                },
            },
        },
    };
```

File: packages/@lwc/integration-karma/test/static-content/x/deepListener/deepListener.html (hunk 3 above)
Comment (nolanlawson) [reply packages/@lwc/integration-karma/test/static-content/x/deepListener/deepListener.html:25]: I thought "shi" was bad luck so I put "yon" 😂

File: packages/@lwc/integration-karma/test/static-content/x/deepListener/deepListener.html [hunk 7]
```diff
@@ -0,0 +1,29 @@
...
+    <div data-id="dynamic3" data-dynamic={dynamic} onfoo={uno.dos.tres}></div>
+    <div>
+        <div data-id="deepStatic3" onfoo={uno.dos.tres}></div>
+    </div>
+
+    <!-- 4 levels deep -->
+    <div data-id="static4" onfoo={ichi.ni.san.yon}></div>
+    <div data-id="dynamic4" data-dynamic={dynamic} onfoo={ichi.ni.san.shi}></div>
+    <div>
+        <div data-id="deepStatic4" onfoo={ichi.ni.san.yon}></div>
```
Comment (nolanlawson) [inline packages/@lwc/integration-karma/test/static-content/x/deepListener/deepListener.html:27]:
```suggestion
        <div data-id="deepStatic4" onfoo={ichi.ni.san.shi}></div>
```

**Review by ekashida — APPROVED** [review]
lgtm, let's wait to see whether the ast changes are bueno

**Review by louis-murray — APPROVED** [review]
